//! The IHO S-57 (edition 3.1) attribute catalogue, as data.
//!
//! Transcribed from IHO S-57 Appendix A, Chapter 2 "Attributes" (edition 3.1,
//! November 2000, iho.int). Any code whose meaning could not be confirmed
//! against the standard is omitted, so unknown codes pass through raw instead
//! of risking a wrong decode.

pub const AttrName = struct { acronym: []const u8, name: []const u8 };

/// Attribute acronym -> the label a mariner reads.
pub const attribute_names = [_]AttrName{
    .{ .acronym = "AGENCY", .name = "Agency" },
    .{ .acronym = "BCNSHP", .name = "Beacon shape" },
    .{ .acronym = "BOYSHP", .name = "Buoy shape" },
    .{ .acronym = "BUISHP", .name = "Building shape" },
    .{ .acronym = "BURDEP", .name = "Buried depth" },
    .{ .acronym = "CALSGN", .name = "Call sign" },
    .{ .acronym = "CATACH", .name = "Category" },
    .{ .acronym = "CATAIR", .name = "Category" },
    .{ .acronym = "CATBRG", .name = "Category" },
    .{ .acronym = "CATBUA", .name = "Category" },
    .{ .acronym = "CATCAM", .name = "Category" },
    .{ .acronym = "CATCAN", .name = "Category" },
    .{ .acronym = "CATCBL", .name = "Category" },
    .{ .acronym = "CATCHP", .name = "Category" },
    .{ .acronym = "CATCOA", .name = "Category" },
    .{ .acronym = "CATCON", .name = "Category" },
    .{ .acronym = "CATCOV", .name = "Category" },
    .{ .acronym = "CATCRN", .name = "Category" },
    .{ .acronym = "CATCTR", .name = "Category" },
    .{ .acronym = "CATDAM", .name = "Category" },
    .{ .acronym = "CATDIS", .name = "Category" },
    .{ .acronym = "CATDOC", .name = "Category" },
    .{ .acronym = "CATDPG", .name = "Category" },
    .{ .acronym = "CATFIF", .name = "Category" },
    .{ .acronym = "CATFNC", .name = "Category" },
    .{ .acronym = "CATFOG", .name = "Category" },
    .{ .acronym = "CATFOR", .name = "Category" },
    .{ .acronym = "CATFRY", .name = "Category" },
    .{ .acronym = "CATGAT", .name = "Category" },
    .{ .acronym = "CATHLK", .name = "Category" },
    .{ .acronym = "CATHAF", .name = "Category" },
    .{ .acronym = "CATICE", .name = "Category" },
    .{ .acronym = "CATINB", .name = "Category" },
    .{ .acronym = "CATLAM", .name = "Category" },
    .{ .acronym = "CATLIT", .name = "Category" },
    .{ .acronym = "CATLMK", .name = "Category" },
    .{ .acronym = "CATLND", .name = "Category" },
    .{ .acronym = "CATMFA", .name = "Category" },
    .{ .acronym = "CATMOR", .name = "Category" },
    .{ .acronym = "CATMPA", .name = "Category" },
    .{ .acronym = "CATNAV", .name = "Category" },
    .{ .acronym = "CATOBS", .name = "Category" },
    .{ .acronym = "CATOFP", .name = "Category" },
    .{ .acronym = "CATOLB", .name = "Category" },
    .{ .acronym = "CATPIL", .name = "Category" },
    .{ .acronym = "CATPIP", .name = "Category" },
    .{ .acronym = "CATPLE", .name = "Category" },
    .{ .acronym = "CATPRA", .name = "Category" },
    .{ .acronym = "CATPYL", .name = "Category" },
    .{ .acronym = "CATQUA", .name = "Category" },
    .{ .acronym = "CATRAS", .name = "Category" },
    .{ .acronym = "CATREA", .name = "Category" },
    .{ .acronym = "CATROD", .name = "Category" },
    .{ .acronym = "CATROS", .name = "Category" },
    .{ .acronym = "CATRSC", .name = "Category" },
    .{ .acronym = "CATRTB", .name = "Category" },
    .{ .acronym = "CATRUN", .name = "Category" },
    .{ .acronym = "CATSCF", .name = "Category" },
    .{ .acronym = "CATSEA", .name = "Category" },
    .{ .acronym = "CATSIL", .name = "Category" },
    .{ .acronym = "CATSIT", .name = "Category" },
    .{ .acronym = "CATSIW", .name = "Category" },
    .{ .acronym = "CATSLC", .name = "Category" },
    .{ .acronym = "CATSLO", .name = "Category" },
    .{ .acronym = "CATSPM", .name = "Category" },
    .{ .acronym = "CATTRK", .name = "Category" },
    .{ .acronym = "CATTSS", .name = "Category" },
    .{ .acronym = "CATVEG", .name = "Category" },
    .{ .acronym = "CATWAT", .name = "Category" },
    .{ .acronym = "CATWED", .name = "Category" },
    .{ .acronym = "CATWRK", .name = "Category" },
    .{ .acronym = "CATZOC", .name = "Category" },
    .{ .acronym = "CAT_TS", .name = "Category" },
    .{ .acronym = "COLOUR", .name = "Colour" },
    .{ .acronym = "COLPAT", .name = "Colour pattern" },
    .{ .acronym = "COMCHA", .name = "Communication channel" },
    .{ .acronym = "CONDTN", .name = "Condition" },
    .{ .acronym = "CONRAD", .name = "Radar conspicuous" },
    .{ .acronym = "CONVIS", .name = "Visually conspicuous" },
    .{ .acronym = "CPDATE", .name = "Compilation date" },
    .{ .acronym = "CSCALE", .name = "Compilation scale" },
    .{ .acronym = "CURVEL", .name = "Current velocity" },
    .{ .acronym = "DATEND", .name = "End date" },
    .{ .acronym = "DATSTA", .name = "Start date" },
    .{ .acronym = "DRVAL1", .name = "Depth range minimum" },
    .{ .acronym = "DRVAL2", .name = "Depth range maximum" },
    .{ .acronym = "DUNITS", .name = "Depth units" },
    .{ .acronym = "ELEVAT", .name = "Elevation" },
    .{ .acronym = "ESTRNG", .name = "Estimated range" },
    .{ .acronym = "EXCLIT", .name = "Light exhibition" },
    .{ .acronym = "EXPSOU", .name = "Exposition of sounding" },
    .{ .acronym = "FUNCTN", .name = "Function" },
    .{ .acronym = "HEIGHT", .name = "Height" },
    .{ .acronym = "HORACC", .name = "Horizontal accuracy" },
    .{ .acronym = "HORCLR", .name = "Horizontal clearance" },
    .{ .acronym = "HORDAT", .name = "Horizontal datum" },
    .{ .acronym = "HORLEN", .name = "Length" },
    .{ .acronym = "HORWID", .name = "Width" },
    .{ .acronym = "HUNITS", .name = "Height/length units" },
    .{ .acronym = "ICEFAC", .name = "Ice factor" },
    .{ .acronym = "INFORM", .name = "Information" },
    .{ .acronym = "JRSDTN", .name = "Jurisdiction" },
    .{ .acronym = "LIFCAP", .name = "Lifting capacity" },
    .{ .acronym = "LITCHR", .name = "Light characteristic" },
    .{ .acronym = "LITVIS", .name = "Light visibility" },
    .{ .acronym = "MARSYS", .name = "Buoyage system" },
    .{ .acronym = "MLTYLT", .name = "Number of lights" },
    .{ .acronym = "NATCON", .name = "Construction" },
    .{ .acronym = "NATION", .name = "Nationality" },
    .{ .acronym = "NATQUA", .name = "Surface qualifier" },
    .{ .acronym = "NATSUR", .name = "Surface" },
    .{ .acronym = "NINFOM", .name = "Information (national)" },
    .{ .acronym = "NMDATE", .name = "Notice to Mariners date" },
    .{ .acronym = "NOBJNM", .name = "Name (national)" },
    .{ .acronym = "NPLDST", .name = "Pilot district (national)" },
    .{ .acronym = "NTXTDS", .name = "Description (national)" },
    .{ .acronym = "OBJNAM", .name = "Name" },
    .{ .acronym = "ORIENT", .name = "Orientation" },
    .{ .acronym = "PEREND", .name = "Period end" },
    .{ .acronym = "PERSTA", .name = "Period start" },
    .{ .acronym = "PICREP", .name = "Picture" },
    .{ .acronym = "PILDST", .name = "Pilot district" },
    .{ .acronym = "POSACC", .name = "Positional accuracy" },
    .{ .acronym = "PRCTRY", .name = "Producing country" },
    .{ .acronym = "PRODCT", .name = "Product" },
    .{ .acronym = "PUBREF", .name = "Publication reference" },
    .{ .acronym = "PUNITS", .name = "Position units" },
    .{ .acronym = "QUAPOS", .name = "Position quality" },
    .{ .acronym = "QUASOU", .name = "Sounding quality" },
    .{ .acronym = "RADIUS", .name = "Radius" },
    .{ .acronym = "RADWAL", .name = "Radar wavelength" },
    .{ .acronym = "RECDAT", .name = "Recording date" },
    .{ .acronym = "RECIND", .name = "Recording indication" },
    .{ .acronym = "RESTRN", .name = "Restriction" },
    .{ .acronym = "RYRMGV", .name = "Reference year" },
    .{ .acronym = "SCAMAX", .name = "Maximum scale" },
    .{ .acronym = "SCAMIN", .name = "Minimum scale" },
    .{ .acronym = "SCVAL1", .name = "Scale value 1" },
    .{ .acronym = "SCVAL2", .name = "Scale value 2" },
    .{ .acronym = "SDISMN", .name = "Minimum sounding distance" },
    .{ .acronym = "SDISMX", .name = "Maximum sounding distance" },
    .{ .acronym = "SECTR1", .name = "Sector limit 1" },
    .{ .acronym = "SECTR2", .name = "Sector limit 2" },
    .{ .acronym = "SHIPAM", .name = "Shift parameters" },
    .{ .acronym = "SIGFRQ", .name = "Signal frequency" },
    .{ .acronym = "SIGGEN", .name = "Signal generation" },
    .{ .acronym = "SIGGRP", .name = "Signal group" },
    .{ .acronym = "SIGPER", .name = "Signal period" },
    .{ .acronym = "SIGSEQ", .name = "Signal sequence" },
    .{ .acronym = "SORDAT", .name = "Source date" },
    .{ .acronym = "SORIND", .name = "Source" },
    .{ .acronym = "SOUACC", .name = "Sounding accuracy" },
    .{ .acronym = "STATUS", .name = "Status" },
    .{ .acronym = "SURATH", .name = "Survey authority" },
    .{ .acronym = "SUREND", .name = "Survey end" },
    .{ .acronym = "SURSTA", .name = "Survey start" },
    .{ .acronym = "SURTYP", .name = "Survey type" },
    .{ .acronym = "TECSOU", .name = "Sounding technique" },
    .{ .acronym = "TIMEND", .name = "End time" },
    .{ .acronym = "TIMSTA", .name = "Start time" },
    .{ .acronym = "TOPSHP", .name = "Topmark shape" },
    .{ .acronym = "TRAFIC", .name = "Traffic flow" },
    .{ .acronym = "TS_TSP", .name = "Tidal stream panel" },
    .{ .acronym = "TS_TSV", .name = "Tidal stream time series" },
    .{ .acronym = "TXTDSC", .name = "Description" },
    .{ .acronym = "T_ACWL", .name = "Water level accuracy" },
    .{ .acronym = "T_HWLW", .name = "High and low waters" },
    .{ .acronym = "T_MTOD", .name = "Tidal prediction method" },
    .{ .acronym = "T_THDF", .name = "Time and height differences" },
    .{ .acronym = "T_TINT", .name = "Time interval" },
    .{ .acronym = "T_TSVL", .name = "Tide time series" },
    .{ .acronym = "T_VAHC", .name = "Harmonic constituents" },
    .{ .acronym = "VALACM", .name = "Annual magnetic change" },
    .{ .acronym = "VALDCO", .name = "Depth contour" },
    .{ .acronym = "VALLMA", .name = "Local magnetic anomaly" },
    .{ .acronym = "VALMAG", .name = "Magnetic variation" },
    .{ .acronym = "VALMXR", .name = "Maximum range" },
    .{ .acronym = "VALNMR", .name = "Nominal range" },
    .{ .acronym = "VALSOU", .name = "Depth" },
    .{ .acronym = "VERACC", .name = "Vertical accuracy" },
    .{ .acronym = "VERCCL", .name = "Vertical clearance (closed)" },
    .{ .acronym = "VERCLR", .name = "Vertical clearance" },
    .{ .acronym = "VERCOP", .name = "Vertical clearance (open)" },
    .{ .acronym = "VERCSA", .name = "Safe vertical clearance" },
    .{ .acronym = "VERDAT", .name = "Vertical datum" },
    .{ .acronym = "VERLEN", .name = "Vertical length" },
    .{ .acronym = "WATLEV", .name = "Water level effect" },
};

pub const EnumValue = struct { acronym: []const u8, code: u16, value: []const u8 };

/// Every enumerated/list attribute's official values, one entry per code.
pub const enum_values = [_]EnumValue{
    .{ .acronym = "BCNSHP", .code = 1, .value = "stake, pole, perch, post" },
    .{ .acronym = "BCNSHP", .code = 2, .value = "withy" },
    .{ .acronym = "BCNSHP", .code = 3, .value = "beacon tower" },
    .{ .acronym = "BCNSHP", .code = 4, .value = "lattice beacon" },
    .{ .acronym = "BCNSHP", .code = 5, .value = "pile beacon" },
    .{ .acronym = "BCNSHP", .code = 6, .value = "cairn" },
    .{ .acronym = "BCNSHP", .code = 7, .value = "buoyant beacon" },
    .{ .acronym = "BOYSHP", .code = 1, .value = "conical (nun, ogival)" },
    .{ .acronym = "BOYSHP", .code = 2, .value = "can (cylindrical)" },
    .{ .acronym = "BOYSHP", .code = 3, .value = "spherical" },
    .{ .acronym = "BOYSHP", .code = 4, .value = "pillar" },
    .{ .acronym = "BOYSHP", .code = 5, .value = "spar (spindle)" },
    .{ .acronym = "BOYSHP", .code = 6, .value = "barrel (tun)" },
    .{ .acronym = "BOYSHP", .code = 7, .value = "super-buoy" },
    .{ .acronym = "BOYSHP", .code = 8, .value = "ice buoy" },
    .{ .acronym = "BUISHP", .code = 1, .value = "no specific shape" },
    .{ .acronym = "BUISHP", .code = 2, .value = "tower" },
    .{ .acronym = "BUISHP", .code = 3, .value = "spire" },
    .{ .acronym = "BUISHP", .code = 4, .value = "cupola (dome)" },
    .{ .acronym = "BUISHP", .code = 5, .value = "high-rise building" },
    .{ .acronym = "BUISHP", .code = 6, .value = "pyramid" },
    .{ .acronym = "BUISHP", .code = 7, .value = "cylindrical" },
    .{ .acronym = "BUISHP", .code = 8, .value = "spherical" },
    .{ .acronym = "BUISHP", .code = 9, .value = "cubic" },
    .{ .acronym = "CATACH", .code = 1, .value = "unrestricted anchorage" },
    .{ .acronym = "CATACH", .code = 2, .value = "deep water anchorage" },
    .{ .acronym = "CATACH", .code = 3, .value = "tanker anchorage" },
    .{ .acronym = "CATACH", .code = 4, .value = "explosives anchorage" },
    .{ .acronym = "CATACH", .code = 5, .value = "quarantine anchorage" },
    .{ .acronym = "CATACH", .code = 6, .value = "sea-plane anchorage" },
    .{ .acronym = "CATACH", .code = 7, .value = "small craft anchorage" },
    .{ .acronym = "CATACH", .code = 8, .value = "small craft mooring area" },
    .{ .acronym = "CATACH", .code = 9, .value = "anchorage for periods up to 24 hours" },
    .{ .acronym = "CATACH", .code = 10, .value = "anchorage for a limited period of time" },
    .{ .acronym = "CATAIR", .code = 1, .value = "military aeroplane airport" },
    .{ .acronym = "CATAIR", .code = 2, .value = "civil aeroplane airport" },
    .{ .acronym = "CATAIR", .code = 3, .value = "military heliport" },
    .{ .acronym = "CATAIR", .code = 4, .value = "civil heliport" },
    .{ .acronym = "CATAIR", .code = 5, .value = "glider airfield" },
    .{ .acronym = "CATAIR", .code = 6, .value = "small planes airfield" },
    .{ .acronym = "CATAIR", .code = 7, .value = "helicopter platform" },
    .{ .acronym = "CATAIR", .code = 8, .value = "emergency airfield" },
    .{ .acronym = "CATBRG", .code = 1, .value = "fixed bridge" },
    .{ .acronym = "CATBRG", .code = 2, .value = "opening bridge" },
    .{ .acronym = "CATBRG", .code = 3, .value = "swing bridge" },
    .{ .acronym = "CATBRG", .code = 4, .value = "lifting bridge" },
    .{ .acronym = "CATBRG", .code = 5, .value = "bascule bridge" },
    .{ .acronym = "CATBRG", .code = 6, .value = "pontoon bridge" },
    .{ .acronym = "CATBRG", .code = 7, .value = "draw bridge" },
    .{ .acronym = "CATBRG", .code = 8, .value = "transporter bridge" },
    .{ .acronym = "CATBRG", .code = 9, .value = "footbridge" },
    .{ .acronym = "CATBRG", .code = 10, .value = "viaduct" },
    .{ .acronym = "CATBRG", .code = 11, .value = "aqueduct" },
    .{ .acronym = "CATBRG", .code = 12, .value = "suspension bridge" },
    .{ .acronym = "CATBUA", .code = 1, .value = "urban area" },
    .{ .acronym = "CATBUA", .code = 2, .value = "settlement" },
    .{ .acronym = "CATBUA", .code = 3, .value = "village" },
    .{ .acronym = "CATBUA", .code = 4, .value = "town" },
    .{ .acronym = "CATBUA", .code = 5, .value = "city" },
    .{ .acronym = "CATBUA", .code = 6, .value = "holiday village" },
    .{ .acronym = "CATCAM", .code = 1, .value = "north cardinal mark" },
    .{ .acronym = "CATCAM", .code = 2, .value = "east cardinal mark" },
    .{ .acronym = "CATCAM", .code = 3, .value = "south cardinal mark" },
    .{ .acronym = "CATCAM", .code = 4, .value = "west cardinal mark" },
    .{ .acronym = "CATCAN", .code = 1, .value = "transportation" },
    .{ .acronym = "CATCAN", .code = 2, .value = "drainage" },
    .{ .acronym = "CATCAN", .code = 3, .value = "irrigation" },
    .{ .acronym = "CATCBL", .code = 1, .value = "power line" },
    .{ .acronym = "CATCBL", .code = 2, .value = "telephone/telegraph" },
    .{ .acronym = "CATCBL", .code = 3, .value = "transmission line" },
    .{ .acronym = "CATCBL", .code = 4, .value = "telephone" },
    .{ .acronym = "CATCBL", .code = 5, .value = "telegraph" },
    .{ .acronym = "CATCBL", .code = 6, .value = "mooring cable/chain" },
    .{ .acronym = "CATCHP", .code = 1, .value = "custom" },
    .{ .acronym = "CATCOA", .code = 1, .value = "steep coast" },
    .{ .acronym = "CATCOA", .code = 2, .value = "flat coast" },
    .{ .acronym = "CATCOA", .code = 3, .value = "sandy shore" },
    .{ .acronym = "CATCOA", .code = 4, .value = "stony shore" },
    .{ .acronym = "CATCOA", .code = 5, .value = "shingly shore" },
    .{ .acronym = "CATCOA", .code = 6, .value = "glacier (seaward end)" },
    .{ .acronym = "CATCOA", .code = 7, .value = "mangrove" },
    .{ .acronym = "CATCOA", .code = 8, .value = "marshy shore" },
    .{ .acronym = "CATCOA", .code = 9, .value = "coral reef" },
    .{ .acronym = "CATCOA", .code = 10, .value = "ice coast" },
    .{ .acronym = "CATCOA", .code = 11, .value = "shelly shore" },
    .{ .acronym = "CATCON", .code = 1, .value = "aerial cableway (telepheric)" },
    .{ .acronym = "CATCON", .code = 2, .value = "belt conveyor" },
    .{ .acronym = "CATCOV", .code = 1, .value = "coverage available" },
    .{ .acronym = "CATCOV", .code = 2, .value = "no coverage available" },
    .{ .acronym = "CATCRN", .code = 1, .value = "crane without specific construction" },
    .{ .acronym = "CATCRN", .code = 2, .value = "container crane/gantry" },
    .{ .acronym = "CATCRN", .code = 3, .value = "sheerlegs" },
    .{ .acronym = "CATCRN", .code = 4, .value = "travelling crane" },
    .{ .acronym = "CATCRN", .code = 5, .value = "A-frame" },
    .{ .acronym = "CATCTR", .code = 1, .value = "triangulation point" },
    .{ .acronym = "CATCTR", .code = 2, .value = "observation spot" },
    .{ .acronym = "CATCTR", .code = 3, .value = "fixed point" },
    .{ .acronym = "CATCTR", .code = 4, .value = "bench-mark" },
    .{ .acronym = "CATCTR", .code = 5, .value = "boundary mark" },
    .{ .acronym = "CATCTR", .code = 6, .value = "horizontal control, main station" },
    .{ .acronym = "CATCTR", .code = 7, .value = "horizontal control, secondary station" },
    .{ .acronym = "CATDAM", .code = 1, .value = "weir" },
    .{ .acronym = "CATDAM", .code = 2, .value = "dam" },
    .{ .acronym = "CATDAM", .code = 3, .value = "flood barrage" },
    .{ .acronym = "CATDIS", .code = 1, .value = "distance mark not physically installed" },
    .{ .acronym = "CATDIS", .code = 2, .value = "visible mark, pole" },
    .{ .acronym = "CATDIS", .code = 3, .value = "visible mark, board" },
    .{ .acronym = "CATDIS", .code = 4, .value = "visible mark, unknown shape" },
    .{ .acronym = "CATDOC", .code = 1, .value = "tidal" },
    .{ .acronym = "CATDOC", .code = 2, .value = "non-tidal (wet dock)" },
    .{ .acronym = "CATDPG", .code = 1, .value = "general dumping ground" },
    .{ .acronym = "CATDPG", .code = 2, .value = "chemical waste dumping ground" },
    .{ .acronym = "CATDPG", .code = 3, .value = "nuclear waste dumping ground" },
    .{ .acronym = "CATDPG", .code = 4, .value = "explosives dumping ground" },
    .{ .acronym = "CATDPG", .code = 5, .value = "spoil ground" },
    .{ .acronym = "CATDPG", .code = 6, .value = "vessel dumping ground" },
    .{ .acronym = "CATFIF", .code = 1, .value = "fishing stake" },
    .{ .acronym = "CATFIF", .code = 2, .value = "fish trap" },
    .{ .acronym = "CATFIF", .code = 3, .value = "fish weir" },
    .{ .acronym = "CATFIF", .code = 4, .value = "tunny net" },
    .{ .acronym = "CATFNC", .code = 1, .value = "fence" },
    .{ .acronym = "CATFNC", .code = 2, .value = "muir" },
    .{ .acronym = "CATFNC", .code = 3, .value = "hedge" },
    .{ .acronym = "CATFNC", .code = 4, .value = "wall" },
    .{ .acronym = "CATFOG", .code = 1, .value = "explosive" },
    .{ .acronym = "CATFOG", .code = 2, .value = "diaphone" },
    .{ .acronym = "CATFOG", .code = 3, .value = "siren" },
    .{ .acronym = "CATFOG", .code = 4, .value = "nautophone" },
    .{ .acronym = "CATFOG", .code = 5, .value = "reed" },
    .{ .acronym = "CATFOG", .code = 6, .value = "tyfon" },
    .{ .acronym = "CATFOG", .code = 7, .value = "bell" },
    .{ .acronym = "CATFOG", .code = 8, .value = "whistle" },
    .{ .acronym = "CATFOG", .code = 9, .value = "gong" },
    .{ .acronym = "CATFOG", .code = 10, .value = "horn" },
    .{ .acronym = "CATFOR", .code = 1, .value = "castle" },
    .{ .acronym = "CATFOR", .code = 2, .value = "fort" },
    .{ .acronym = "CATFOR", .code = 3, .value = "battery" },
    .{ .acronym = "CATFOR", .code = 4, .value = "blockhouse" },
    .{ .acronym = "CATFOR", .code = 5, .value = "Martello tower" },
    .{ .acronym = "CATFOR", .code = 6, .value = "redoubt" },
    .{ .acronym = "CATFRY", .code = 1, .value = "'free-moving' ferry" },
    .{ .acronym = "CATFRY", .code = 2, .value = "cable ferry" },
    .{ .acronym = "CATFRY", .code = 3, .value = "ice ferry" },
    .{ .acronym = "CATGAT", .code = 1, .value = "gate in general" },
    .{ .acronym = "CATGAT", .code = 2, .value = "flood barrage gate" },
    .{ .acronym = "CATGAT", .code = 3, .value = "caisson" },
    .{ .acronym = "CATGAT", .code = 4, .value = "lock gate" },
    .{ .acronym = "CATGAT", .code = 5, .value = "dyke gate" },
    .{ .acronym = "CATGAT", .code = 6, .value = "sluice" },
    .{ .acronym = "CATHLK", .code = 1, .value = "floating restaurant" },
    .{ .acronym = "CATHLK", .code = 2, .value = "historic ship" },
    .{ .acronym = "CATHLK", .code = 3, .value = "museum" },
    .{ .acronym = "CATHLK", .code = 4, .value = "accommodation" },
    .{ .acronym = "CATHLK", .code = 5, .value = "floating breakwater" },
    .{ .acronym = "CATHAF", .code = 1, .value = "RoRo-terminal" },
    .{ .acronym = "CATHAF", .code = 2, .value = "timber yard" },
    .{ .acronym = "CATHAF", .code = 3, .value = "ferry terminal" },
    .{ .acronym = "CATHAF", .code = 4, .value = "fishing harbour" },
    .{ .acronym = "CATHAF", .code = 5, .value = "yacht harbour/marina" },
    .{ .acronym = "CATHAF", .code = 6, .value = "naval base" },
    .{ .acronym = "CATHAF", .code = 7, .value = "tanker terminal" },
    .{ .acronym = "CATHAF", .code = 8, .value = "passenger terminal" },
    .{ .acronym = "CATHAF", .code = 9, .value = "shipyard" },
    .{ .acronym = "CATHAF", .code = 10, .value = "container terminal" },
    .{ .acronym = "CATHAF", .code = 11, .value = "bulk terminal" },
    .{ .acronym = "CATHAF", .code = 12, .value = "syncrolift" },
    .{ .acronym = "CATHAF", .code = 13, .value = "straddle carrier" },
    .{ .acronym = "CATICE", .code = 1, .value = "fast ice" },
    .{ .acronym = "CATICE", .code = 2, .value = "sea ice" },
    .{ .acronym = "CATICE", .code = 3, .value = "growler area" },
    .{ .acronym = "CATICE", .code = 4, .value = "pancake ice" },
    .{ .acronym = "CATICE", .code = 5, .value = "glacier" },
    .{ .acronym = "CATICE", .code = 6, .value = "ice peak" },
    .{ .acronym = "CATICE", .code = 7, .value = "pack ice" },
    .{ .acronym = "CATICE", .code = 8, .value = "polar ice" },
    .{ .acronym = "CATINB", .code = 1, .value = "catenary anchor leg mooring (CALM)" },
    .{ .acronym = "CATINB", .code = 2, .value = "single buoy mooring (SBM or SPM)" },
    .{ .acronym = "CATLAM", .code = 1, .value = "port-hand lateral mark" },
    .{ .acronym = "CATLAM", .code = 2, .value = "starboard-hand lateral mark" },
    .{ .acronym = "CATLAM", .code = 3, .value = "preferred channel to starboard lateral mark" },
    .{ .acronym = "CATLAM", .code = 4, .value = "preferred channel to port lateral mark" },
    .{ .acronym = "CATLIT", .code = 1, .value = "directional function" },
    .{ .acronym = "CATLIT", .code = 2, .value = "rear/upper light" },
    .{ .acronym = "CATLIT", .code = 3, .value = "front/lower light" },
    .{ .acronym = "CATLIT", .code = 4, .value = "leading light" },
    .{ .acronym = "CATLIT", .code = 5, .value = "aero light" },
    .{ .acronym = "CATLIT", .code = 6, .value = "air obstruction light" },
    .{ .acronym = "CATLIT", .code = 7, .value = "fog detector light" },
    .{ .acronym = "CATLIT", .code = 8, .value = "flood light" },
    .{ .acronym = "CATLIT", .code = 9, .value = "strip light" },
    .{ .acronym = "CATLIT", .code = 10, .value = "subsidiary light" },
    .{ .acronym = "CATLIT", .code = 11, .value = "spotlight" },
    .{ .acronym = "CATLIT", .code = 12, .value = "front" },
    .{ .acronym = "CATLIT", .code = 13, .value = "rear" },
    .{ .acronym = "CATLIT", .code = 14, .value = "lower" },
    .{ .acronym = "CATLIT", .code = 15, .value = "upper" },
    .{ .acronym = "CATLIT", .code = 16, .value = "moiré effect" },
    .{ .acronym = "CATLIT", .code = 17, .value = "emergency" },
    .{ .acronym = "CATLIT", .code = 18, .value = "bearing light" },
    .{ .acronym = "CATLIT", .code = 19, .value = "horizontally disposed" },
    .{ .acronym = "CATLIT", .code = 20, .value = "vertically disposed" },
    .{ .acronym = "CATLMK", .code = 1, .value = "cairn" },
    .{ .acronym = "CATLMK", .code = 2, .value = "cemetery" },
    .{ .acronym = "CATLMK", .code = 3, .value = "chimney" },
    .{ .acronym = "CATLMK", .code = 4, .value = "dish aerial" },
    .{ .acronym = "CATLMK", .code = 5, .value = "flagstaff (flagpole)" },
    .{ .acronym = "CATLMK", .code = 6, .value = "flare stack" },
    .{ .acronym = "CATLMK", .code = 7, .value = "mast" },
    .{ .acronym = "CATLMK", .code = 8, .value = "windsock" },
    .{ .acronym = "CATLMK", .code = 9, .value = "monument" },
    .{ .acronym = "CATLMK", .code = 10, .value = "column (pillar)" },
    .{ .acronym = "CATLMK", .code = 11, .value = "memorial plaque" },
    .{ .acronym = "CATLMK", .code = 12, .value = "obelisk" },
    .{ .acronym = "CATLMK", .code = 13, .value = "statue" },
    .{ .acronym = "CATLMK", .code = 14, .value = "cross" },
    .{ .acronym = "CATLMK", .code = 15, .value = "dome" },
    .{ .acronym = "CATLMK", .code = 16, .value = "radar scanner" },
    .{ .acronym = "CATLMK", .code = 17, .value = "tower" },
    .{ .acronym = "CATLMK", .code = 18, .value = "windmill" },
    .{ .acronym = "CATLMK", .code = 19, .value = "windmotor" },
    .{ .acronym = "CATLMK", .code = 20, .value = "spire/minaret" },
    .{ .acronym = "CATLMK", .code = 21, .value = "large rock or boulder on land" },
    .{ .acronym = "CATLND", .code = 1, .value = "fen" },
    .{ .acronym = "CATLND", .code = 2, .value = "marsh" },
    .{ .acronym = "CATLND", .code = 3, .value = "moor/bog" },
    .{ .acronym = "CATLND", .code = 4, .value = "heathland" },
    .{ .acronym = "CATLND", .code = 5, .value = "mountain range" },
    .{ .acronym = "CATLND", .code = 6, .value = "lowlands" },
    .{ .acronym = "CATLND", .code = 7, .value = "canyon lands" },
    .{ .acronym = "CATLND", .code = 8, .value = "paddy field" },
    .{ .acronym = "CATLND", .code = 9, .value = "agricultural land" },
    .{ .acronym = "CATLND", .code = 10, .value = "savanna/grassland" },
    .{ .acronym = "CATLND", .code = 11, .value = "parkland" },
    .{ .acronym = "CATLND", .code = 12, .value = "swamp" },
    .{ .acronym = "CATLND", .code = 13, .value = "landslide" },
    .{ .acronym = "CATLND", .code = 14, .value = "lava flow" },
    .{ .acronym = "CATLND", .code = 15, .value = "salt pan" },
    .{ .acronym = "CATLND", .code = 16, .value = "moraine" },
    .{ .acronym = "CATLND", .code = 17, .value = "crater" },
    .{ .acronym = "CATLND", .code = 18, .value = "cave" },
    .{ .acronym = "CATLND", .code = 19, .value = "rock column or pinnacle" },
    .{ .acronym = "CATLND", .code = 20, .value = "cay" },
    .{ .acronym = "CATMFA", .code = 1, .value = "crustaceans" },
    .{ .acronym = "CATMFA", .code = 2, .value = "oysters/mussels" },
    .{ .acronym = "CATMFA", .code = 3, .value = "fish" },
    .{ .acronym = "CATMFA", .code = 4, .value = "seaweed" },
    .{ .acronym = "CATMFA", .code = 5, .value = "pearl culture farm" },
    .{ .acronym = "CATMOR", .code = 1, .value = "dolphin" },
    .{ .acronym = "CATMOR", .code = 2, .value = "deviation dolphin" },
    .{ .acronym = "CATMOR", .code = 3, .value = "bollard" },
    .{ .acronym = "CATMOR", .code = 4, .value = "tie-up wall" },
    .{ .acronym = "CATMOR", .code = 5, .value = "post or pile" },
    .{ .acronym = "CATMOR", .code = 6, .value = "chain/wire/cable" },
    .{ .acronym = "CATMOR", .code = 7, .value = "mooring buoy" },
    .{ .acronym = "CATMPA", .code = 1, .value = "practice area in general" },
    .{ .acronym = "CATMPA", .code = 2, .value = "torpedo exercise area" },
    .{ .acronym = "CATMPA", .code = 3, .value = "submarine exercise area" },
    .{ .acronym = "CATMPA", .code = 4, .value = "firing danger area" },
    .{ .acronym = "CATMPA", .code = 5, .value = "mine-laying practice area" },
    .{ .acronym = "CATMPA", .code = 6, .value = "small arms firing range" },
    .{ .acronym = "CATNAV", .code = 1, .value = "clearing line" },
    .{ .acronym = "CATNAV", .code = 2, .value = "transit line" },
    .{ .acronym = "CATNAV", .code = 3, .value = "leading line bearing a recommended track" },
    .{ .acronym = "CATOBS", .code = 1, .value = "snag/stump" },
    .{ .acronym = "CATOBS", .code = 2, .value = "wellhead" },
    .{ .acronym = "CATOBS", .code = 3, .value = "diffuser" },
    .{ .acronym = "CATOBS", .code = 4, .value = "crib" },
    .{ .acronym = "CATOBS", .code = 5, .value = "fish haven" },
    .{ .acronym = "CATOBS", .code = 6, .value = "foul area" },
    .{ .acronym = "CATOBS", .code = 7, .value = "foul ground" },
    .{ .acronym = "CATOBS", .code = 8, .value = "ice boom" },
    .{ .acronym = "CATOBS", .code = 9, .value = "ground tackle" },
    .{ .acronym = "CATOBS", .code = 10, .value = "boom" },
    .{ .acronym = "CATOFP", .code = 1, .value = "oil derrick/rig" },
    .{ .acronym = "CATOFP", .code = 2, .value = "production platform" },
    .{ .acronym = "CATOFP", .code = 3, .value = "observation/research platform" },
    .{ .acronym = "CATOFP", .code = 4, .value = "articulated loading platform (ALP)" },
    .{ .acronym = "CATOFP", .code = 5, .value = "single anchor leg mooring (SALM)" },
    .{ .acronym = "CATOFP", .code = 6, .value = "mooring tower" },
    .{ .acronym = "CATOFP", .code = 7, .value = "artificial island" },
    .{
        .acronym = "CATOFP",
        .code = 8,
        .value = "floating production, storage and off-loading vessel (FPSO)",
    },
    .{ .acronym = "CATOFP", .code = 9, .value = "accommodation platform" },
    .{
        .acronym = "CATOFP",
        .code = 10,
        .value = "navigation, communication and control buoy (NCCB)",
    },
    .{ .acronym = "CATOLB", .code = 1, .value = "oil retention (high pressure pipe)" },
    .{ .acronym = "CATOLB", .code = 2, .value = "floating oil barrier" },
    .{ .acronym = "CATPIL", .code = 1, .value = "boarding by pilot-cruising vessel" },
    .{ .acronym = "CATPIL", .code = 2, .value = "boarding by helicopter" },
    .{ .acronym = "CATPIL", .code = 3, .value = "pilot comes out from shore" },
    .{ .acronym = "CATPIP", .code = 1, .value = "pipeline in general" },
    .{ .acronym = "CATPIP", .code = 2, .value = "outfall pipe" },
    .{ .acronym = "CATPIP", .code = 3, .value = "intake pipe" },
    .{ .acronym = "CATPIP", .code = 4, .value = "sewer" },
    .{ .acronym = "CATPIP", .code = 5, .value = "bubbler system" },
    .{ .acronym = "CATPIP", .code = 6, .value = "supply pipe" },
    .{ .acronym = "CATPLE", .code = 1, .value = "stake" },
    .{ .acronym = "CATPLE", .code = 2, .value = "snag" },
    .{ .acronym = "CATPLE", .code = 3, .value = "post" },
    .{ .acronym = "CATPLE", .code = 4, .value = "tripodal" },
    .{ .acronym = "CATPRA", .code = 1, .value = "quarry" },
    .{ .acronym = "CATPRA", .code = 2, .value = "mine" },
    .{ .acronym = "CATPRA", .code = 3, .value = "stockpile" },
    .{ .acronym = "CATPRA", .code = 4, .value = "power station area" },
    .{ .acronym = "CATPRA", .code = 5, .value = "refinery area" },
    .{ .acronym = "CATPRA", .code = 6, .value = "timber yard" },
    .{ .acronym = "CATPRA", .code = 7, .value = "factory area" },
    .{ .acronym = "CATPRA", .code = 8, .value = "tank farm" },
    .{ .acronym = "CATPRA", .code = 9, .value = "wind farm" },
    .{ .acronym = "CATPRA", .code = 10, .value = "slag heap/spoil heap" },
    .{ .acronym = "CATPYL", .code = 1, .value = "power transmission pylon/pole" },
    .{ .acronym = "CATPYL", .code = 2, .value = "telephone/telegraph pylon/pole" },
    .{ .acronym = "CATPYL", .code = 3, .value = "aerial cableway/sky pylon" },
    .{ .acronym = "CATPYL", .code = 4, .value = "bridge pylon/tower" },
    .{ .acronym = "CATPYL", .code = 5, .value = "bridge pier" },
    .{ .acronym = "CATQUA", .code = 1, .value = "data quality A" },
    .{ .acronym = "CATQUA", .code = 2, .value = "data quality B" },
    .{ .acronym = "CATQUA", .code = 3, .value = "data quality C" },
    .{ .acronym = "CATQUA", .code = 4, .value = "data quality D" },
    .{ .acronym = "CATQUA", .code = 5, .value = "data quality E" },
    .{ .acronym = "CATQUA", .code = 6, .value = "quality not evaluated" },
    .{ .acronym = "CATRAS", .code = 1, .value = "radar surveillance station" },
    .{ .acronym = "CATRAS", .code = 2, .value = "coast radar station" },
    .{ .acronym = "CATREA", .code = 1, .value = "offshore safety zone" },
    .{ .acronym = "CATREA", .code = 2, .value = "anchoring prohibition area" },
    .{ .acronym = "CATREA", .code = 3, .value = "fishing prohibition area" },
    .{ .acronym = "CATREA", .code = 4, .value = "nature reserve" },
    .{ .acronym = "CATREA", .code = 5, .value = "bird sanctuary" },
    .{ .acronym = "CATREA", .code = 6, .value = "game reserve" },
    .{ .acronym = "CATREA", .code = 7, .value = "seal sanctuary" },
    .{ .acronym = "CATREA", .code = 8, .value = "degaussing range" },
    .{ .acronym = "CATREA", .code = 9, .value = "military area" },
    .{ .acronym = "CATREA", .code = 10, .value = "historic wreck area" },
    .{ .acronym = "CATREA", .code = 11, .value = "inshore traffic zone" },
    .{ .acronym = "CATREA", .code = 12, .value = "navigational aid safety zone" },
    .{ .acronym = "CATREA", .code = 13, .value = "danger of stranding area" },
    .{ .acronym = "CATREA", .code = 14, .value = "minefield" },
    .{ .acronym = "CATREA", .code = 15, .value = "diving prohibition area" },
    .{ .acronym = "CATREA", .code = 16, .value = "area to be avoided" },
    .{ .acronym = "CATREA", .code = 17, .value = "prohibited area" },
    .{ .acronym = "CATREA", .code = 18, .value = "swimming area" },
    .{ .acronym = "CATREA", .code = 19, .value = "waiting area" },
    .{ .acronym = "CATREA", .code = 20, .value = "research area" },
    .{ .acronym = "CATREA", .code = 21, .value = "dredging area" },
    .{ .acronym = "CATREA", .code = 22, .value = "fish sanctuary" },
    .{ .acronym = "CATREA", .code = 23, .value = "ecological reserve" },
    .{ .acronym = "CATREA", .code = 24, .value = "no wake area" },
    .{ .acronym = "CATREA", .code = 25, .value = "swinging area" },
    .{ .acronym = "CATREA", .code = 26, .value = "water skiing area" },
    .{ .acronym = "CATROD", .code = 1, .value = "motorway" },
    .{ .acronym = "CATROD", .code = 2, .value = "major road" },
    .{ .acronym = "CATROD", .code = 3, .value = "minor road" },
    .{ .acronym = "CATROD", .code = 4, .value = "track/path" },
    .{ .acronym = "CATROD", .code = 5, .value = "major street" },
    .{ .acronym = "CATROD", .code = 6, .value = "minor street" },
    .{ .acronym = "CATROD", .code = 7, .value = "crossing" },
    .{
        .acronym = "CATROS",
        .code = 1,
        .value = "circular (non-directional) marine or aero-marine radiobeacon",
    },
    .{ .acronym = "CATROS", .code = 2, .value = "directional radiobeacon" },
    .{ .acronym = "CATROS", .code = 3, .value = "rotating-pattern radiobeacon" },
    .{ .acronym = "CATROS", .code = 4, .value = "Consol beacon" },
    .{ .acronym = "CATROS", .code = 5, .value = "radio direction-finding station" },
    .{ .acronym = "CATROS", .code = 6, .value = "coast radio station providing QTG service" },
    .{ .acronym = "CATROS", .code = 7, .value = "aeronautical radiobeacon" },
    .{ .acronym = "CATROS", .code = 8, .value = "Decca" },
    .{ .acronym = "CATROS", .code = 9, .value = "Loran C" },
    .{ .acronym = "CATROS", .code = 10, .value = "Differential GPS" },
    .{ .acronym = "CATROS", .code = 11, .value = "Toran" },
    .{ .acronym = "CATROS", .code = 12, .value = "Omega" },
    .{ .acronym = "CATROS", .code = 13, .value = "Syledis" },
    .{ .acronym = "CATROS", .code = 14, .value = "Chaika (Chayka)" },
    .{ .acronym = "CATRSC", .code = 1, .value = "rescue station with lifeboat" },
    .{ .acronym = "CATRSC", .code = 2, .value = "rescue station with rocket" },
    .{ .acronym = "CATRSC", .code = 3, .value = "rescue station with lifeboat and rocket" },
    .{ .acronym = "CATRSC", .code = 4, .value = "refuge for shipwrecked mariners" },
    .{ .acronym = "CATRSC", .code = 5, .value = "refuge for intertidal area walkers" },
    .{ .acronym = "CATRSC", .code = 6, .value = "lifeboat lying at a mooring" },
    .{ .acronym = "CATRSC", .code = 7, .value = "aid radio station" },
    .{ .acronym = "CATRSC", .code = 8, .value = "first aid equipment" },
    .{ .acronym = "CATRTB", .code = 1, .value = "ramark, radar beacon transmitting continuously" },
    .{ .acronym = "CATRTB", .code = 2, .value = "racon, radar transponder beacon" },
    .{ .acronym = "CATRTB", .code = 3, .value = "leading racon/radar transponder beacon" },
    .{ .acronym = "CATRUN", .code = 1, .value = "aeroplane runway" },
    .{ .acronym = "CATRUN", .code = 2, .value = "helicopter landing pad" },
    .{ .acronym = "CATSCF", .code = 1, .value = "visitor's berth" },
    .{ .acronym = "CATSCF", .code = 2, .value = "nautical club" },
    .{ .acronym = "CATSCF", .code = 3, .value = "boat hoist" },
    .{ .acronym = "CATSCF", .code = 4, .value = "sailmaker" },
    .{ .acronym = "CATSCF", .code = 5, .value = "boatyard" },
    .{ .acronym = "CATSCF", .code = 6, .value = "public inn" },
    .{ .acronym = "CATSCF", .code = 7, .value = "restaurant" },
    .{ .acronym = "CATSCF", .code = 8, .value = "chandler" },
    .{ .acronym = "CATSCF", .code = 9, .value = "provisions" },
    .{ .acronym = "CATSCF", .code = 10, .value = "doctor" },
    .{ .acronym = "CATSCF", .code = 11, .value = "pharmacy" },
    .{ .acronym = "CATSCF", .code = 12, .value = "water tap" },
    .{ .acronym = "CATSCF", .code = 13, .value = "fuel station" },
    .{ .acronym = "CATSCF", .code = 14, .value = "electricity" },
    .{ .acronym = "CATSCF", .code = 15, .value = "bottle gas" },
    .{ .acronym = "CATSCF", .code = 16, .value = "showers" },
    .{ .acronym = "CATSCF", .code = 17, .value = "launderette" },
    .{ .acronym = "CATSCF", .code = 18, .value = "public toilets" },
    .{ .acronym = "CATSCF", .code = 19, .value = "post box" },
    .{ .acronym = "CATSCF", .code = 20, .value = "public telephone" },
    .{ .acronym = "CATSCF", .code = 21, .value = "refuse bin" },
    .{ .acronym = "CATSCF", .code = 22, .value = "car park" },
    .{ .acronym = "CATSCF", .code = 23, .value = "parking for boats and trailers" },
    .{ .acronym = "CATSCF", .code = 24, .value = "caravan site" },
    .{ .acronym = "CATSCF", .code = 25, .value = "camping site" },
    .{ .acronym = "CATSCF", .code = 26, .value = "sewerage pump-out station" },
    .{ .acronym = "CATSCF", .code = 27, .value = "emergency telephone" },
    .{ .acronym = "CATSCF", .code = 28, .value = "landing/launching place for boats" },
    .{ .acronym = "CATSCF", .code = 29, .value = "visitors mooring" },
    .{ .acronym = "CATSCF", .code = 30, .value = "scrubbing berth" },
    .{ .acronym = "CATSCF", .code = 31, .value = "picnic area" },
    .{ .acronym = "CATSCF", .code = 32, .value = "mechanics workshop" },
    .{ .acronym = "CATSCF", .code = 33, .value = "guard and/or security service" },
    .{ .acronym = "CATSEA", .code = 1, .value = "sea area in general" },
    .{ .acronym = "CATSEA", .code = 2, .value = "gat" },
    .{ .acronym = "CATSEA", .code = 3, .value = "bank" },
    .{ .acronym = "CATSEA", .code = 4, .value = "deep" },
    .{ .acronym = "CATSEA", .code = 5, .value = "bay" },
    .{ .acronym = "CATSEA", .code = 6, .value = "trench" },
    .{ .acronym = "CATSEA", .code = 7, .value = "basin" },
    .{ .acronym = "CATSEA", .code = 8, .value = "mud flats" },
    .{ .acronym = "CATSEA", .code = 9, .value = "reef" },
    .{ .acronym = "CATSEA", .code = 10, .value = "ledge" },
    .{ .acronym = "CATSEA", .code = 11, .value = "canyon" },
    .{ .acronym = "CATSEA", .code = 12, .value = "narrows" },
    .{ .acronym = "CATSEA", .code = 13, .value = "shoal" },
    .{ .acronym = "CATSEA", .code = 14, .value = "knoll" },
    .{ .acronym = "CATSEA", .code = 15, .value = "ridge" },
    .{ .acronym = "CATSEA", .code = 16, .value = "seamount" },
    .{ .acronym = "CATSEA", .code = 17, .value = "pinnacle" },
    .{ .acronym = "CATSEA", .code = 18, .value = "abyssal plain" },
    .{ .acronym = "CATSEA", .code = 19, .value = "plateau" },
    .{ .acronym = "CATSEA", .code = 20, .value = "spur" },
    .{ .acronym = "CATSEA", .code = 21, .value = "shelf" },
    .{ .acronym = "CATSEA", .code = 22, .value = "trough" },
    .{ .acronym = "CATSEA", .code = 23, .value = "saddle" },
    .{ .acronym = "CATSEA", .code = 24, .value = "abyssal hills" },
    .{ .acronym = "CATSEA", .code = 25, .value = "apron" },
    .{ .acronym = "CATSEA", .code = 26, .value = "archipelagic apron" },
    .{ .acronym = "CATSEA", .code = 27, .value = "borderland" },
    .{ .acronym = "CATSEA", .code = 28, .value = "continental margin" },
    .{ .acronym = "CATSEA", .code = 29, .value = "continental rise" },
    .{ .acronym = "CATSEA", .code = 30, .value = "escarpment" },
    .{ .acronym = "CATSEA", .code = 31, .value = "fan" },
    .{ .acronym = "CATSEA", .code = 32, .value = "fracture zone" },
    .{ .acronym = "CATSEA", .code = 33, .value = "gap" },
    .{ .acronym = "CATSEA", .code = 34, .value = "guyot" },
    .{ .acronym = "CATSEA", .code = 35, .value = "hill" },
    .{ .acronym = "CATSEA", .code = 36, .value = "hole" },
    .{ .acronym = "CATSEA", .code = 37, .value = "levee" },
    .{ .acronym = "CATSEA", .code = 38, .value = "median valley" },
    .{ .acronym = "CATSEA", .code = 39, .value = "moat" },
    .{ .acronym = "CATSEA", .code = 40, .value = "mountains" },
    .{ .acronym = "CATSEA", .code = 41, .value = "peak" },
    .{ .acronym = "CATSEA", .code = 42, .value = "province" },
    .{ .acronym = "CATSEA", .code = 43, .value = "rise" },
    .{ .acronym = "CATSEA", .code = 44, .value = "sea channel" },
    .{ .acronym = "CATSEA", .code = 45, .value = "seamount chain" },
    .{ .acronym = "CATSEA", .code = 46, .value = "shelf-edge" },
    .{ .acronym = "CATSEA", .code = 47, .value = "sill" },
    .{ .acronym = "CATSEA", .code = 48, .value = "slope" },
    .{ .acronym = "CATSEA", .code = 49, .value = "terrace" },
    .{ .acronym = "CATSEA", .code = 50, .value = "valley" },
    .{ .acronym = "CATSEA", .code = 51, .value = "canal" },
    .{ .acronym = "CATSEA", .code = 52, .value = "lake" },
    .{ .acronym = "CATSEA", .code = 53, .value = "river" },
    .{ .acronym = "CATSEA", .code = 54, .value = "reach" },
    .{ .acronym = "CATSIL", .code = 1, .value = "silo in general" },
    .{ .acronym = "CATSIL", .code = 2, .value = "tank in general" },
    .{ .acronym = "CATSIL", .code = 3, .value = "grain elevator" },
    .{ .acronym = "CATSIL", .code = 4, .value = "water tower" },
    .{ .acronym = "CATSIT", .code = 1, .value = "port control" },
    .{ .acronym = "CATSIT", .code = 2, .value = "port entry and departure" },
    .{ .acronym = "CATSIT", .code = 3, .value = "International Port Traffic" },
    .{ .acronym = "CATSIT", .code = 4, .value = "berthing" },
    .{ .acronym = "CATSIT", .code = 5, .value = "dock" },
    .{ .acronym = "CATSIT", .code = 6, .value = "lock" },
    .{ .acronym = "CATSIT", .code = 7, .value = "flood barrage" },
    .{ .acronym = "CATSIT", .code = 8, .value = "bridge passage" },
    .{ .acronym = "CATSIT", .code = 9, .value = "dredging" },
    .{ .acronym = "CATSIT", .code = 10, .value = "traffic control light" },
    .{ .acronym = "CATSIW", .code = 1, .value = "danger" },
    .{ .acronym = "CATSIW", .code = 2, .value = "maritime obstruction" },
    .{ .acronym = "CATSIW", .code = 3, .value = "cable" },
    .{ .acronym = "CATSIW", .code = 4, .value = "military practice" },
    .{ .acronym = "CATSIW", .code = 5, .value = "distress" },
    .{ .acronym = "CATSIW", .code = 6, .value = "weather" },
    .{ .acronym = "CATSIW", .code = 7, .value = "storm" },
    .{ .acronym = "CATSIW", .code = 8, .value = "ice" },
    .{ .acronym = "CATSIW", .code = 9, .value = "time" },
    .{ .acronym = "CATSIW", .code = 10, .value = "tide" },
    .{ .acronym = "CATSIW", .code = 11, .value = "tidal stream" },
    .{ .acronym = "CATSIW", .code = 12, .value = "tide gauge" },
    .{ .acronym = "CATSIW", .code = 13, .value = "tide scale" },
    .{ .acronym = "CATSIW", .code = 14, .value = "diving" },
    .{ .acronym = "CATSIW", .code = 15, .value = "water level gauge" },
    .{ .acronym = "CATSLC", .code = 1, .value = "breakwater" },
    .{ .acronym = "CATSLC", .code = 2, .value = "groyne (groin)" },
    .{ .acronym = "CATSLC", .code = 3, .value = "mole" },
    .{ .acronym = "CATSLC", .code = 4, .value = "pier (jetty)" },
    .{ .acronym = "CATSLC", .code = 5, .value = "promenade pier" },
    .{ .acronym = "CATSLC", .code = 6, .value = "wharf (quay)" },
    .{ .acronym = "CATSLC", .code = 7, .value = "training wall" },
    .{ .acronym = "CATSLC", .code = 8, .value = "rip rap" },
    .{ .acronym = "CATSLC", .code = 9, .value = "revetment" },
    .{ .acronym = "CATSLC", .code = 10, .value = "sea wall" },
    .{ .acronym = "CATSLC", .code = 11, .value = "landing steps" },
    .{ .acronym = "CATSLC", .code = 12, .value = "ramp" },
    .{ .acronym = "CATSLC", .code = 13, .value = "slipway" },
    .{ .acronym = "CATSLC", .code = 14, .value = "fender" },
    .{ .acronym = "CATSLC", .code = 15, .value = "solid face wharf" },
    .{ .acronym = "CATSLC", .code = 16, .value = "open face wharf" },
    .{ .acronym = "CATSLC", .code = 17, .value = "log ramp" },
    .{ .acronym = "CATSLO", .code = 1, .value = "cutting" },
    .{ .acronym = "CATSLO", .code = 2, .value = "embankment" },
    .{ .acronym = "CATSLO", .code = 3, .value = "dune" },
    .{ .acronym = "CATSLO", .code = 4, .value = "hill" },
    .{ .acronym = "CATSLO", .code = 5, .value = "pingo" },
    .{ .acronym = "CATSLO", .code = 6, .value = "cliff" },
    .{ .acronym = "CATSLO", .code = 7, .value = "scree" },
    .{ .acronym = "CATSPM", .code = 1, .value = "firing danger area mark" },
    .{ .acronym = "CATSPM", .code = 2, .value = "target mark" },
    .{ .acronym = "CATSPM", .code = 3, .value = "marker ship mark" },
    .{ .acronym = "CATSPM", .code = 4, .value = "degaussing range mark" },
    .{ .acronym = "CATSPM", .code = 5, .value = "barge mark" },
    .{ .acronym = "CATSPM", .code = 6, .value = "cable mark" },
    .{ .acronym = "CATSPM", .code = 7, .value = "spoil ground mark" },
    .{ .acronym = "CATSPM", .code = 8, .value = "outfall mark" },
    .{ .acronym = "CATSPM", .code = 9, .value = "ODAS (Ocean-Data-Acquisition-System)" },
    .{ .acronym = "CATSPM", .code = 10, .value = "recording mark" },
    .{ .acronym = "CATSPM", .code = 11, .value = "seaplane anchorage mark" },
    .{ .acronym = "CATSPM", .code = 12, .value = "recreation zone mark" },
    .{ .acronym = "CATSPM", .code = 13, .value = "private mark" },
    .{ .acronym = "CATSPM", .code = 14, .value = "mooring mark" },
    .{ .acronym = "CATSPM", .code = 15, .value = "LANBY (Large Automatic Navigational Buoy)" },
    .{ .acronym = "CATSPM", .code = 16, .value = "leading mark" },
    .{ .acronym = "CATSPM", .code = 17, .value = "measured distance mark" },
    .{ .acronym = "CATSPM", .code = 18, .value = "notice mark" },
    .{ .acronym = "CATSPM", .code = 19, .value = "TSS mark (Traffic Separation Scheme)" },
    .{ .acronym = "CATSPM", .code = 20, .value = "anchoring prohibited mark" },
    .{ .acronym = "CATSPM", .code = 21, .value = "berthing prohibited mark" },
    .{ .acronym = "CATSPM", .code = 22, .value = "overtaking prohibited mark" },
    .{ .acronym = "CATSPM", .code = 23, .value = "two-way traffic prohibited mark" },
    .{ .acronym = "CATSPM", .code = 24, .value = "'reduced wake' mark" },
    .{ .acronym = "CATSPM", .code = 25, .value = "speed limit mark" },
    .{ .acronym = "CATSPM", .code = 26, .value = "stop mark" },
    .{ .acronym = "CATSPM", .code = 27, .value = "general warning mark" },
    .{ .acronym = "CATSPM", .code = 28, .value = "'sound ship's siren' mark" },
    .{ .acronym = "CATSPM", .code = 29, .value = "restricted vertical clearance mark" },
    .{ .acronym = "CATSPM", .code = 30, .value = "maximum vessel's draught mark" },
    .{ .acronym = "CATSPM", .code = 31, .value = "restricted horizontal clearance mark" },
    .{ .acronym = "CATSPM", .code = 32, .value = "strong current warning mark" },
    .{ .acronym = "CATSPM", .code = 33, .value = "berthing permitted mark" },
    .{ .acronym = "CATSPM", .code = 34, .value = "overhead power cable mark" },
    .{ .acronym = "CATSPM", .code = 35, .value = "'channel edge gradient' mark" },
    .{ .acronym = "CATSPM", .code = 36, .value = "telephone mark" },
    .{ .acronym = "CATSPM", .code = 37, .value = "ferry crossing mark" },
    .{ .acronym = "CATSPM", .code = 38, .value = "marine traffic lights" },
    .{ .acronym = "CATSPM", .code = 39, .value = "pipeline mark" },
    .{ .acronym = "CATSPM", .code = 40, .value = "anchorage mark" },
    .{ .acronym = "CATSPM", .code = 41, .value = "clearing mark" },
    .{ .acronym = "CATSPM", .code = 42, .value = "control mark" },
    .{ .acronym = "CATSPM", .code = 43, .value = "diving mark" },
    .{ .acronym = "CATSPM", .code = 44, .value = "refuge beacon" },
    .{ .acronym = "CATSPM", .code = 45, .value = "foul ground mark" },
    .{ .acronym = "CATSPM", .code = 46, .value = "yachting mark" },
    .{ .acronym = "CATSPM", .code = 47, .value = "heliport mark" },
    .{ .acronym = "CATSPM", .code = 48, .value = "GPS mark" },
    .{ .acronym = "CATSPM", .code = 49, .value = "seaplane landing mark" },
    .{ .acronym = "CATSPM", .code = 50, .value = "entry prohibited mark" },
    .{ .acronym = "CATSPM", .code = 51, .value = "work in progress mark" },
    .{ .acronym = "CATSPM", .code = 52, .value = "mark with unknown purpose" },
    .{ .acronym = "CATSPM", .code = 53, .value = "wellhead mark" },
    .{ .acronym = "CATSPM", .code = 54, .value = "channel separation mark" },
    .{ .acronym = "CATSPM", .code = 55, .value = "marine farm mark" },
    .{ .acronym = "CATSPM", .code = 56, .value = "artificial reef mark" },
    .{ .acronym = "CATTRK", .code = 1, .value = "based on a system of fixed marks" },
    .{ .acronym = "CATTRK", .code = 2, .value = "not based on a system of fixed marks" },
    .{ .acronym = "CATTSS", .code = 1, .value = "IMO - adopted" },
    .{ .acronym = "CATTSS", .code = 2, .value = "not IMO - adopted" },
    .{ .acronym = "CATVEG", .code = 1, .value = "grass" },
    .{ .acronym = "CATVEG", .code = 2, .value = "paddy field" },
    .{ .acronym = "CATVEG", .code = 3, .value = "bush" },
    .{ .acronym = "CATVEG", .code = 4, .value = "deciduous wood" },
    .{ .acronym = "CATVEG", .code = 5, .value = "coniferous wood" },
    .{ .acronym = "CATVEG", .code = 6, .value = "wood in general (inc mixed wood)" },
    .{ .acronym = "CATVEG", .code = 7, .value = "mangroves" },
    .{ .acronym = "CATVEG", .code = 8, .value = "park" },
    .{ .acronym = "CATVEG", .code = 9, .value = "parkland" },
    .{ .acronym = "CATVEG", .code = 10, .value = "mixed crops" },
    .{ .acronym = "CATVEG", .code = 11, .value = "reed" },
    .{ .acronym = "CATVEG", .code = 12, .value = "moss" },
    .{ .acronym = "CATVEG", .code = 13, .value = "tree in general" },
    .{ .acronym = "CATVEG", .code = 14, .value = "evergreen tree" },
    .{ .acronym = "CATVEG", .code = 15, .value = "coniferous tree" },
    .{ .acronym = "CATVEG", .code = 16, .value = "palm tree" },
    .{ .acronym = "CATVEG", .code = 17, .value = "nipa palm tree" },
    .{ .acronym = "CATVEG", .code = 18, .value = "casuarina tree" },
    .{ .acronym = "CATVEG", .code = 19, .value = "eucalypt tree" },
    .{ .acronym = "CATVEG", .code = 20, .value = "deciduous tree" },
    .{ .acronym = "CATVEG", .code = 21, .value = "mangrove tree" },
    .{ .acronym = "CATVEG", .code = 22, .value = "filao tree" },
    .{ .acronym = "CATWAT", .code = 1, .value = "breakers" },
    .{ .acronym = "CATWAT", .code = 2, .value = "eddies" },
    .{ .acronym = "CATWAT", .code = 3, .value = "overfalls" },
    .{ .acronym = "CATWAT", .code = 4, .value = "tide rips" },
    .{ .acronym = "CATWAT", .code = 5, .value = "bombora" },
    .{ .acronym = "CATWED", .code = 1, .value = "kelp" },
    .{ .acronym = "CATWED", .code = 2, .value = "sea weed" },
    .{ .acronym = "CATWED", .code = 3, .value = "sea grass" },
    .{ .acronym = "CATWED", .code = 4, .value = "saragasso" },
    .{ .acronym = "CATWRK", .code = 1, .value = "non-dangerous wreck" },
    .{ .acronym = "CATWRK", .code = 2, .value = "dangerous wreck" },
    .{ .acronym = "CATWRK", .code = 3, .value = "distributed remains of wreck" },
    .{ .acronym = "CATWRK", .code = 4, .value = "wreck showing mast/masts" },
    .{
        .acronym = "CATWRK",
        .code = 5,
        .value = "wreck showing any portion of hull or superstructure",
    },
    .{ .acronym = "CATZOC", .code = 1, .value = "zone of confidence A1" },
    .{ .acronym = "CATZOC", .code = 2, .value = "zone of confidence A2" },
    .{ .acronym = "CATZOC", .code = 3, .value = "zone of confidence B" },
    .{ .acronym = "CATZOC", .code = 4, .value = "zone of confidence C" },
    .{ .acronym = "CATZOC", .code = 5, .value = "zone of confidence D" },
    .{ .acronym = "CATZOC", .code = 6, .value = "zone of confidence U (data not assessed)" },
    .{ .acronym = "CAT_TS", .code = 1, .value = "flood stream" },
    .{ .acronym = "CAT_TS", .code = 2, .value = "ebb stream" },
    .{ .acronym = "CAT_TS", .code = 3, .value = "other tidal flow" },
    .{ .acronym = "COLOUR", .code = 1, .value = "White" },
    .{ .acronym = "COLOUR", .code = 2, .value = "Black" },
    .{ .acronym = "COLOUR", .code = 3, .value = "Red" },
    .{ .acronym = "COLOUR", .code = 4, .value = "Green" },
    .{ .acronym = "COLOUR", .code = 5, .value = "Blue" },
    .{ .acronym = "COLOUR", .code = 6, .value = "Yellow" },
    .{ .acronym = "COLOUR", .code = 7, .value = "Grey" },
    .{ .acronym = "COLOUR", .code = 8, .value = "Brown" },
    .{ .acronym = "COLOUR", .code = 9, .value = "Amber" },
    .{ .acronym = "COLOUR", .code = 10, .value = "Violet" },
    .{ .acronym = "COLOUR", .code = 11, .value = "Orange" },
    .{ .acronym = "COLOUR", .code = 12, .value = "Magenta" },
    .{ .acronym = "COLOUR", .code = 13, .value = "Pink" },
    .{ .acronym = "COLPAT", .code = 1, .value = "horizontal stripes" },
    .{ .acronym = "COLPAT", .code = 2, .value = "vertical stripes" },
    .{ .acronym = "COLPAT", .code = 3, .value = "diagonal stripes" },
    .{ .acronym = "COLPAT", .code = 4, .value = "squared" },
    .{ .acronym = "COLPAT", .code = 5, .value = "stripes (direction unknown)" },
    .{ .acronym = "COLPAT", .code = 6, .value = "border stripe" },
    .{ .acronym = "CONDTN", .code = 1, .value = "under construction" },
    .{ .acronym = "CONDTN", .code = 2, .value = "ruined" },
    .{ .acronym = "CONDTN", .code = 3, .value = "under reclamation" },
    .{ .acronym = "CONDTN", .code = 4, .value = "wingless" },
    .{ .acronym = "CONDTN", .code = 5, .value = "planned construction" },
    .{ .acronym = "CONRAD", .code = 1, .value = "radar conspicuous" },
    .{ .acronym = "CONRAD", .code = 2, .value = "not radar conspicuous" },
    .{ .acronym = "CONRAD", .code = 3, .value = "radar conspicuous (has radar reflector)" },
    .{ .acronym = "CONVIS", .code = 1, .value = "visually conspicuous" },
    .{ .acronym = "CONVIS", .code = 2, .value = "not visually conspicuous" },
    .{ .acronym = "DUNITS", .code = 1, .value = "metres" },
    .{ .acronym = "DUNITS", .code = 2, .value = "fathoms and feet" },
    .{ .acronym = "DUNITS", .code = 3, .value = "feet" },
    .{ .acronym = "DUNITS", .code = 4, .value = "fathoms and fractions" },
    .{ .acronym = "EXCLIT", .code = 1, .value = "light shown without change of character" },
    .{ .acronym = "EXCLIT", .code = 2, .value = "daytime light" },
    .{ .acronym = "EXCLIT", .code = 3, .value = "fog light" },
    .{ .acronym = "EXCLIT", .code = 4, .value = "night light" },
    .{
        .acronym = "EXPSOU",
        .code = 1,
        .value = "within the range of depth of the surrounding depth area",
    },
    .{
        .acronym = "EXPSOU",
        .code = 2,
        .value = "shoaler than the range of depth of the surrounding depth area",
    },
    .{
        .acronym = "EXPSOU",
        .code = 3,
        .value = "deeper than the range of depth of the surrounding depth area",
    },
    .{ .acronym = "FUNCTN", .code = 1, .value = "no function/service of major interest" },
    .{ .acronym = "FUNCTN", .code = 2, .value = "harbour-master's office" },
    .{ .acronym = "FUNCTN", .code = 3, .value = "custom office" },
    .{ .acronym = "FUNCTN", .code = 4, .value = "health office" },
    .{ .acronym = "FUNCTN", .code = 5, .value = "hospital" },
    .{ .acronym = "FUNCTN", .code = 6, .value = "post office" },
    .{ .acronym = "FUNCTN", .code = 7, .value = "hotel" },
    .{ .acronym = "FUNCTN", .code = 8, .value = "railway station" },
    .{ .acronym = "FUNCTN", .code = 9, .value = "police station" },
    .{ .acronym = "FUNCTN", .code = 10, .value = "water-police station" },
    .{ .acronym = "FUNCTN", .code = 11, .value = "pilot office" },
    .{ .acronym = "FUNCTN", .code = 12, .value = "pilot lookout" },
    .{ .acronym = "FUNCTN", .code = 13, .value = "bank office" },
    .{ .acronym = "FUNCTN", .code = 14, .value = "headquarters for district control" },
    .{ .acronym = "FUNCTN", .code = 15, .value = "transit shed/warehouse" },
    .{ .acronym = "FUNCTN", .code = 16, .value = "factory" },
    .{ .acronym = "FUNCTN", .code = 17, .value = "power station" },
    .{ .acronym = "FUNCTN", .code = 18, .value = "administrative" },
    .{ .acronym = "FUNCTN", .code = 19, .value = "educational facility" },
    .{ .acronym = "FUNCTN", .code = 20, .value = "church" },
    .{ .acronym = "FUNCTN", .code = 21, .value = "chapel" },
    .{ .acronym = "FUNCTN", .code = 22, .value = "temple" },
    .{ .acronym = "FUNCTN", .code = 23, .value = "pagoda" },
    .{ .acronym = "FUNCTN", .code = 24, .value = "shinto shrine" },
    .{ .acronym = "FUNCTN", .code = 25, .value = "buddhist temple" },
    .{ .acronym = "FUNCTN", .code = 26, .value = "mosque" },
    .{ .acronym = "FUNCTN", .code = 27, .value = "marabout" },
    .{ .acronym = "FUNCTN", .code = 28, .value = "lookout" },
    .{ .acronym = "FUNCTN", .code = 29, .value = "communication" },
    .{ .acronym = "FUNCTN", .code = 30, .value = "television" },
    .{ .acronym = "FUNCTN", .code = 31, .value = "radio" },
    .{ .acronym = "FUNCTN", .code = 32, .value = "radar" },
    .{ .acronym = "FUNCTN", .code = 33, .value = "light support" },
    .{ .acronym = "FUNCTN", .code = 34, .value = "microwave" },
    .{ .acronym = "FUNCTN", .code = 35, .value = "cooling" },
    .{ .acronym = "FUNCTN", .code = 36, .value = "observation" },
    .{ .acronym = "FUNCTN", .code = 37, .value = "timeball" },
    .{ .acronym = "FUNCTN", .code = 38, .value = "clock" },
    .{ .acronym = "FUNCTN", .code = 39, .value = "control" },
    .{ .acronym = "FUNCTN", .code = 40, .value = "airship mooring" },
    .{ .acronym = "FUNCTN", .code = 41, .value = "stadium" },
    .{ .acronym = "FUNCTN", .code = 42, .value = "bus station" },
    .{ .acronym = "HORDAT", .code = 1, .value = "WGS 72" },
    .{ .acronym = "HORDAT", .code = 2, .value = "WGS 84" },
    .{ .acronym = "HORDAT", .code = 3, .value = "European 1950" },
    .{ .acronym = "HORDAT", .code = 4, .value = "Potsdam Datum" },
    .{ .acronym = "HORDAT", .code = 5, .value = "Adindan" },
    .{ .acronym = "HORDAT", .code = 6, .value = "Afgooye" },
    .{ .acronym = "HORDAT", .code = 7, .value = "Ain el Abd 1970" },
    .{ .acronym = "HORDAT", .code = 8, .value = "Anna 1 Astro 1965" },
    .{ .acronym = "HORDAT", .code = 9, .value = "Antigua Island Astro 1943" },
    .{ .acronym = "HORDAT", .code = 10, .value = "Arc 1950" },
    .{ .acronym = "HORDAT", .code = 11, .value = "Arc 1960" },
    .{ .acronym = "HORDAT", .code = 12, .value = "Ascension Island 1958" },
    .{ .acronym = "HORDAT", .code = 13, .value = "Astro beacon \"E\" 1945" },
    .{ .acronym = "HORDAT", .code = 14, .value = "Astro DOS 71/4" },
    .{ .acronym = "HORDAT", .code = 15, .value = "Astro Tern Island (FRIG) 1961" },
    .{ .acronym = "HORDAT", .code = 16, .value = "Astronomical Station 1952" },
    .{ .acronym = "HORDAT", .code = 17, .value = "Australian Geodetic 1966" },
    .{ .acronym = "HORDAT", .code = 18, .value = "Australian Geodetic 1984" },
    .{ .acronym = "HORDAT", .code = 19, .value = "Ayabelle Lighthouse" },
    .{ .acronym = "HORDAT", .code = 20, .value = "Bellevue (IGN)" },
    .{ .acronym = "HORDAT", .code = 21, .value = "Bermuda 1957" },
    .{ .acronym = "HORDAT", .code = 22, .value = "Bissau" },
    .{ .acronym = "HORDAT", .code = 23, .value = "Bogota Observatory" },
    .{ .acronym = "HORDAT", .code = 24, .value = "Bukit Rimpah" },
    .{ .acronym = "HORDAT", .code = 25, .value = "Camp Area Astro" },
    .{ .acronym = "HORDAT", .code = 26, .value = "Campo Inchauspe 1969" },
    .{ .acronym = "HORDAT", .code = 27, .value = "Canton Astro 1966" },
    .{ .acronym = "HORDAT", .code = 28, .value = "Cape" },
    .{ .acronym = "HORDAT", .code = 29, .value = "Cape Canaveral" },
    .{ .acronym = "HORDAT", .code = 30, .value = "Carthage" },
    .{ .acronym = "HORDAT", .code = 31, .value = "Chatam Island Astro 1971" },
    .{ .acronym = "HORDAT", .code = 32, .value = "Chua Astro" },
    .{ .acronym = "HORDAT", .code = 33, .value = "Corrego Alegre" },
    .{ .acronym = "HORDAT", .code = 34, .value = "Dabola" },
    .{ .acronym = "HORDAT", .code = 35, .value = "Djakarta (Batavia)" },
    .{ .acronym = "HORDAT", .code = 36, .value = "DOS 1968" },
    .{ .acronym = "HORDAT", .code = 37, .value = "Easter Island 1967" },
    .{ .acronym = "HORDAT", .code = 38, .value = "European 1979" },
    .{ .acronym = "HORDAT", .code = 39, .value = "Fort Thomas 1955" },
    .{ .acronym = "HORDAT", .code = 40, .value = "Gan 1970" },
    .{ .acronym = "HORDAT", .code = 41, .value = "Geodetic Datum 1949" },
    .{ .acronym = "HORDAT", .code = 42, .value = "Graciosa Base SW 1948" },
    .{ .acronym = "HORDAT", .code = 43, .value = "Guam 1963" },
    .{ .acronym = "HORDAT", .code = 44, .value = "Gunung Segara" },
    .{ .acronym = "HORDAT", .code = 45, .value = "GUX 1 Astro" },
    .{ .acronym = "HORDAT", .code = 46, .value = "Herat North" },
    .{ .acronym = "HORDAT", .code = 47, .value = "Hjorsey 1955" },
    .{ .acronym = "HORDAT", .code = 48, .value = "Hong Kong 1963" },
    .{ .acronym = "HORDAT", .code = 49, .value = "Hu-Tzu-Shan" },
    .{ .acronym = "HORDAT", .code = 50, .value = "Indian" },
    .{ .acronym = "HORDAT", .code = 51, .value = "Indian 1954" },
    .{ .acronym = "HORDAT", .code = 52, .value = "Indian 1975" },
    .{ .acronym = "HORDAT", .code = 53, .value = "Ireland 1965" },
    .{ .acronym = "HORDAT", .code = 54, .value = "ISTS 061 Astro 1968" },
    .{ .acronym = "HORDAT", .code = 55, .value = "ISTS 073 Astro 1969" },
    .{ .acronym = "HORDAT", .code = 56, .value = "Johnston Island 1961" },
    .{ .acronym = "HORDAT", .code = 57, .value = "Kandawala" },
    .{ .acronym = "HORDAT", .code = 58, .value = "Kerguelen Island 1949" },
    .{ .acronym = "HORDAT", .code = 59, .value = "Kertau 1948" },
    .{ .acronym = "HORDAT", .code = 60, .value = "Kusaie Astro 1951" },
    .{ .acronym = "HORDAT", .code = 61, .value = "L. C. 5 Astro 1961" },
    .{ .acronym = "HORDAT", .code = 62, .value = "Leigon" },
    .{ .acronym = "HORDAT", .code = 63, .value = "Liberia 1964" },
    .{ .acronym = "HORDAT", .code = 64, .value = "Luzon" },
    .{ .acronym = "HORDAT", .code = 65, .value = "Mahe 1971" },
    .{ .acronym = "HORDAT", .code = 66, .value = "Massawa" },
    .{ .acronym = "HORDAT", .code = 67, .value = "Merchich" },
    .{ .acronym = "HORDAT", .code = 68, .value = "Midway Astro 1961" },
    .{ .acronym = "HORDAT", .code = 69, .value = "Minna" },
    .{ .acronym = "HORDAT", .code = 70, .value = "Montserrat Island Astro 1958" },
    .{ .acronym = "HORDAT", .code = 71, .value = "M'Poraloko" },
    .{ .acronym = "HORDAT", .code = 72, .value = "Nahrwan" },
    .{ .acronym = "HORDAT", .code = 73, .value = "Naparima, BWI" },
    .{ .acronym = "HORDAT", .code = 74, .value = "North American 1927" },
    .{ .acronym = "HORDAT", .code = 75, .value = "North American 1983" },
    .{ .acronym = "HORDAT", .code = 76, .value = "Observatorio Meteorologico 1939" },
    .{ .acronym = "HORDAT", .code = 77, .value = "Old Egyptian 1907" },
    .{ .acronym = "HORDAT", .code = 78, .value = "Old Hawaiian" },
    .{ .acronym = "HORDAT", .code = 79, .value = "Oman" },
    .{ .acronym = "HORDAT", .code = 80, .value = "Ordnance Survey of Great Britain 1936" },
    .{ .acronym = "HORDAT", .code = 81, .value = "Pico de las Nieves" },
    .{ .acronym = "HORDAT", .code = 82, .value = "Pitcairn Astro 1967" },
    .{ .acronym = "HORDAT", .code = 83, .value = "Point 58" },
    .{ .acronym = "HORDAT", .code = 84, .value = "Pointe Noire 1948" },
    .{ .acronym = "HORDAT", .code = 85, .value = "Porto Santo 1936" },
    .{ .acronym = "HORDAT", .code = 86, .value = "Provisional South American 1956" },
    .{
        .acronym = "HORDAT",
        .code = 87,
        .value = "Provisional South Chilean 1963 (also known as Hito XVIII 1963)",
    },
    .{ .acronym = "HORDAT", .code = 88, .value = "Puerto Rico" },
    .{ .acronym = "HORDAT", .code = 89, .value = "Qatar national" },
    .{ .acronym = "HORDAT", .code = 90, .value = "Qornoq" },
    .{ .acronym = "HORDAT", .code = 91, .value = "Reunion" },
    .{ .acronym = "HORDAT", .code = 92, .value = "Rome 1940" },
    .{ .acronym = "HORDAT", .code = 93, .value = "Santo (DOS) 1965" },
    .{ .acronym = "HORDAT", .code = 94, .value = "Sao Braz" },
    .{ .acronym = "HORDAT", .code = 95, .value = "Sapper Hill 1943" },
    .{ .acronym = "HORDAT", .code = 96, .value = "Schwarzeck" },
    .{ .acronym = "HORDAT", .code = 97, .value = "Selvagem Grande 1938" },
    .{ .acronym = "HORDAT", .code = 98, .value = "South American 1969" },
    .{ .acronym = "HORDAT", .code = 99, .value = "South Asia" },
    .{ .acronym = "HORDAT", .code = 100, .value = "Tananarive Observatory 1925" },
    .{ .acronym = "HORDAT", .code = 101, .value = "Timbalai 1948" },
    .{ .acronym = "HORDAT", .code = 102, .value = "Tokyo" },
    .{ .acronym = "HORDAT", .code = 103, .value = "Tristan Astro 1968" },
    .{ .acronym = "HORDAT", .code = 104, .value = "Viti Levu 1916" },
    .{ .acronym = "HORDAT", .code = 105, .value = "Wake-Eniwetok 1960" },
    .{ .acronym = "HORDAT", .code = 106, .value = "Wake Island Astro 1952" },
    .{ .acronym = "HORDAT", .code = 107, .value = "Yacare" },
    .{ .acronym = "HORDAT", .code = 108, .value = "Zanderij" },
    .{ .acronym = "HORDAT", .code = 109, .value = "American Samoa 1962" },
    .{ .acronym = "HORDAT", .code = 110, .value = "Deception Island" },
    .{ .acronym = "HORDAT", .code = 111, .value = "Indian 1960" },
    .{ .acronym = "HORDAT", .code = 112, .value = "Indonesian 1974" },
    .{ .acronym = "HORDAT", .code = 113, .value = "North Sahara 1959" },
    .{ .acronym = "HORDAT", .code = 114, .value = "Pulkovo 1942" },
    .{ .acronym = "HORDAT", .code = 115, .value = "S-42 (Pulkovo 1942)" },
    .{ .acronym = "HORDAT", .code = 116, .value = "S-JYSK" },
    .{ .acronym = "HORDAT", .code = 117, .value = "Voirol 1950" },
    .{ .acronym = "HORDAT", .code = 118, .value = "Average Terrestrial System 1977" },
    .{ .acronym = "HORDAT", .code = 119, .value = "Compensation Géodésique du Québec 1977" },
    .{ .acronym = "HORDAT", .code = 120, .value = "Finnish (KKJ)" },
    .{ .acronym = "HORDAT", .code = 121, .value = "Ordnance Survey of Ireland" },
    .{ .acronym = "HORDAT", .code = 122, .value = "Revised Kertau" },
    .{ .acronym = "HORDAT", .code = 123, .value = "Revised Nahrwan" },
    .{ .acronym = "HORDAT", .code = 124, .value = "GGRS 76 (Greece)" },
    .{ .acronym = "HORDAT", .code = 125, .value = "Nouvelle Triangulation de France" },
    .{ .acronym = "HORDAT", .code = 126, .value = "RT 90 (Sweden)" },
    .{ .acronym = "HORDAT", .code = 127, .value = "Geocentric Datum of Australia (GDA)" },
    .{ .acronym = "HORDAT", .code = 128, .value = "BJZ54 (A954 Beijing Coordinates)" },
    .{ .acronym = "HORDAT", .code = 129, .value = "Modified BJZ54" },
    .{ .acronym = "HORDAT", .code = 130, .value = "GDZ80" },
    .{ .acronym = "HORDAT", .code = 131, .value = "Local datum" },
    .{ .acronym = "HUNITS", .code = 1, .value = "metres" },
    .{ .acronym = "HUNITS", .code = 2, .value = "feet" },
    .{ .acronym = "JRSDTN", .code = 1, .value = "international" },
    .{ .acronym = "JRSDTN", .code = 2, .value = "national" },
    .{ .acronym = "JRSDTN", .code = 3, .value = "national sub-division" },
    .{ .acronym = "LITCHR", .code = 1, .value = "Fixed" },
    .{ .acronym = "LITCHR", .code = 2, .value = "Flashing" },
    .{ .acronym = "LITCHR", .code = 3, .value = "Long-flashing" },
    .{ .acronym = "LITCHR", .code = 4, .value = "Quick-flashing" },
    .{ .acronym = "LITCHR", .code = 5, .value = "Very quick-flashing" },
    .{ .acronym = "LITCHR", .code = 6, .value = "Ultra quick-flashing" },
    .{ .acronym = "LITCHR", .code = 7, .value = "Isophased" },
    .{ .acronym = "LITCHR", .code = 8, .value = "Occulting" },
    .{ .acronym = "LITCHR", .code = 9, .value = "Interrupted quick-flashing" },
    .{ .acronym = "LITCHR", .code = 10, .value = "Interrupted very quick-flashing" },
    .{ .acronym = "LITCHR", .code = 11, .value = "Interrupted ultra quick-flashing" },
    .{ .acronym = "LITCHR", .code = 12, .value = "Morse" },
    .{ .acronym = "LITCHR", .code = 13, .value = "Fixed/flash" },
    .{ .acronym = "LITCHR", .code = 14, .value = "Flash/long-flash" },
    .{ .acronym = "LITCHR", .code = 15, .value = "Occulting/flash" },
    .{ .acronym = "LITCHR", .code = 16, .value = "Fixed/long-flash" },
    .{ .acronym = "LITCHR", .code = 17, .value = "Occulting alternating" },
    .{ .acronym = "LITCHR", .code = 18, .value = "Long-flash alternating" },
    .{ .acronym = "LITCHR", .code = 19, .value = "Flash alternating" },
    .{ .acronym = "LITCHR", .code = 20, .value = "Group alternating" },
    .{ .acronym = "LITCHR", .code = 21, .value = "2 fixed (vertical)" },
    .{ .acronym = "LITCHR", .code = 22, .value = "2 fixed (horizontal)" },
    .{ .acronym = "LITCHR", .code = 23, .value = "3 fixed (vertical)" },
    .{ .acronym = "LITCHR", .code = 24, .value = "3 fixed (horizontal)" },
    .{ .acronym = "LITCHR", .code = 25, .value = "Quick-flash plus long-flash" },
    .{ .acronym = "LITCHR", .code = 26, .value = "Very quick-flash plus long-flash" },
    .{ .acronym = "LITCHR", .code = 27, .value = "Ultra quick-flash plus long-flash" },
    .{ .acronym = "LITCHR", .code = 28, .value = "Alternating" },
    .{ .acronym = "LITCHR", .code = 29, .value = "Fixed and alternating flashing" },
    .{ .acronym = "LITVIS", .code = 1, .value = "high intensity" },
    .{ .acronym = "LITVIS", .code = 2, .value = "low intensity" },
    .{ .acronym = "LITVIS", .code = 3, .value = "faint" },
    .{ .acronym = "LITVIS", .code = 4, .value = "intensified" },
    .{ .acronym = "LITVIS", .code = 5, .value = "unintensified" },
    .{ .acronym = "LITVIS", .code = 6, .value = "visibility deliberately restricted" },
    .{ .acronym = "LITVIS", .code = 7, .value = "obscured" },
    .{ .acronym = "LITVIS", .code = 8, .value = "partially obscured" },
    .{ .acronym = "MARSYS", .code = 1, .value = "IALA A" },
    .{ .acronym = "MARSYS", .code = 2, .value = "IALA B" },
    .{ .acronym = "MARSYS", .code = 3, .value = "modified US" },
    .{ .acronym = "MARSYS", .code = 4, .value = "old US" },
    .{ .acronym = "MARSYS", .code = 5, .value = "US intracoastal waterway" },
    .{ .acronym = "MARSYS", .code = 6, .value = "US uniform state" },
    .{ .acronym = "MARSYS", .code = 7, .value = "US western rivers" },
    .{ .acronym = "MARSYS", .code = 8, .value = "SIGNI" },
    .{ .acronym = "MARSYS", .code = 9, .value = "no system" },
    .{ .acronym = "MARSYS", .code = 10, .value = "other system" },
    .{ .acronym = "NATCON", .code = 1, .value = "masonry" },
    .{ .acronym = "NATCON", .code = 2, .value = "concreted" },
    .{ .acronym = "NATCON", .code = 3, .value = "loose boulders" },
    .{ .acronym = "NATCON", .code = 4, .value = "hard surfaced" },
    .{ .acronym = "NATCON", .code = 5, .value = "unsurfaced" },
    .{ .acronym = "NATCON", .code = 6, .value = "wooden" },
    .{ .acronym = "NATCON", .code = 7, .value = "metal" },
    .{ .acronym = "NATCON", .code = 8, .value = "glass reinforced plastic (GRP)" },
    .{ .acronym = "NATCON", .code = 9, .value = "painted" },
    .{ .acronym = "NATQUA", .code = 1, .value = "fine" },
    .{ .acronym = "NATQUA", .code = 2, .value = "medium" },
    .{ .acronym = "NATQUA", .code = 3, .value = "coarse" },
    .{ .acronym = "NATQUA", .code = 4, .value = "broken" },
    .{ .acronym = "NATQUA", .code = 5, .value = "sticky" },
    .{ .acronym = "NATQUA", .code = 6, .value = "soft" },
    .{ .acronym = "NATQUA", .code = 7, .value = "stiff" },
    .{ .acronym = "NATQUA", .code = 8, .value = "volcanic" },
    .{ .acronym = "NATQUA", .code = 9, .value = "calcareous" },
    .{ .acronym = "NATQUA", .code = 10, .value = "hard" },
    .{ .acronym = "NATSUR", .code = 1, .value = "mud" },
    .{ .acronym = "NATSUR", .code = 2, .value = "clay" },
    .{ .acronym = "NATSUR", .code = 3, .value = "silt" },
    .{ .acronym = "NATSUR", .code = 4, .value = "sand" },
    .{ .acronym = "NATSUR", .code = 5, .value = "stone" },
    .{ .acronym = "NATSUR", .code = 6, .value = "gravel" },
    .{ .acronym = "NATSUR", .code = 7, .value = "pebbles" },
    .{ .acronym = "NATSUR", .code = 8, .value = "cobbles" },
    .{ .acronym = "NATSUR", .code = 9, .value = "rock" },
    .{ .acronym = "NATSUR", .code = 10, .value = "marsh" },
    .{ .acronym = "NATSUR", .code = 11, .value = "lava" },
    .{ .acronym = "NATSUR", .code = 12, .value = "snow" },
    .{ .acronym = "NATSUR", .code = 13, .value = "ice" },
    .{ .acronym = "NATSUR", .code = 14, .value = "coral" },
    .{ .acronym = "NATSUR", .code = 15, .value = "swamp" },
    .{ .acronym = "NATSUR", .code = 16, .value = "bog/moor" },
    .{ .acronym = "NATSUR", .code = 17, .value = "shells" },
    .{ .acronym = "NATSUR", .code = 18, .value = "boulder" },
    .{ .acronym = "PRODCT", .code = 1, .value = "oil" },
    .{ .acronym = "PRODCT", .code = 2, .value = "gas" },
    .{ .acronym = "PRODCT", .code = 3, .value = "water" },
    .{ .acronym = "PRODCT", .code = 4, .value = "stone" },
    .{ .acronym = "PRODCT", .code = 5, .value = "coal" },
    .{ .acronym = "PRODCT", .code = 6, .value = "ore" },
    .{ .acronym = "PRODCT", .code = 7, .value = "chemicals" },
    .{ .acronym = "PRODCT", .code = 8, .value = "drinking water" },
    .{ .acronym = "PRODCT", .code = 9, .value = "milk" },
    .{ .acronym = "PRODCT", .code = 10, .value = "bauxite" },
    .{ .acronym = "PRODCT", .code = 11, .value = "coke" },
    .{ .acronym = "PRODCT", .code = 12, .value = "iron ingots" },
    .{ .acronym = "PRODCT", .code = 13, .value = "salt" },
    .{ .acronym = "PRODCT", .code = 14, .value = "sand" },
    .{ .acronym = "PRODCT", .code = 15, .value = "timber" },
    .{ .acronym = "PRODCT", .code = 16, .value = "sawdust/wood chips" },
    .{ .acronym = "PRODCT", .code = 17, .value = "scrap metal" },
    .{ .acronym = "PRODCT", .code = 18, .value = "liquified natural gas (LNG)" },
    .{ .acronym = "PRODCT", .code = 19, .value = "liquified petroleum gas (LPG)" },
    .{ .acronym = "PRODCT", .code = 20, .value = "wine" },
    .{ .acronym = "PRODCT", .code = 21, .value = "cement" },
    .{ .acronym = "PRODCT", .code = 22, .value = "grain" },
    .{ .acronym = "PUNITS", .code = 1, .value = "metres" },
    .{ .acronym = "PUNITS", .code = 2, .value = "degrees of arc" },
    .{ .acronym = "PUNITS", .code = 3, .value = "millimeters" },
    .{ .acronym = "PUNITS", .code = 4, .value = "feet" },
    .{ .acronym = "PUNITS", .code = 5, .value = "cables" },
    .{ .acronym = "QUAPOS", .code = 1, .value = "surveyed" },
    .{ .acronym = "QUAPOS", .code = 2, .value = "unsurveyed" },
    .{ .acronym = "QUAPOS", .code = 3, .value = "inadequately surveyed" },
    .{ .acronym = "QUAPOS", .code = 4, .value = "approximate" },
    .{ .acronym = "QUAPOS", .code = 5, .value = "position doubtful" },
    .{ .acronym = "QUAPOS", .code = 6, .value = "unreliable" },
    .{ .acronym = "QUAPOS", .code = 7, .value = "reported (not surveyed)" },
    .{ .acronym = "QUAPOS", .code = 8, .value = "reported (not confirmed)" },
    .{ .acronym = "QUAPOS", .code = 9, .value = "estimated" },
    .{ .acronym = "QUAPOS", .code = 10, .value = "precisely known" },
    .{ .acronym = "QUAPOS", .code = 11, .value = "calculated" },
    .{ .acronym = "QUASOU", .code = 1, .value = "depth known" },
    .{ .acronym = "QUASOU", .code = 2, .value = "depth unknown" },
    .{ .acronym = "QUASOU", .code = 3, .value = "doubtful sounding" },
    .{ .acronym = "QUASOU", .code = 4, .value = "unreliable sounding" },
    .{ .acronym = "QUASOU", .code = 5, .value = "no bottom found at value shown" },
    .{ .acronym = "QUASOU", .code = 6, .value = "least depth known" },
    .{
        .acronym = "QUASOU",
        .code = 7,
        .value = "least depth unknown, safe clearance at value shown",
    },
    .{ .acronym = "QUASOU", .code = 8, .value = "value reported (not surveyed)" },
    .{ .acronym = "QUASOU", .code = 9, .value = "value reported (not confirmed)" },
    .{ .acronym = "QUASOU", .code = 10, .value = "maintained depth" },
    .{ .acronym = "QUASOU", .code = 11, .value = "not regularly maintained" },
    .{ .acronym = "RESTRN", .code = 1, .value = "anchoring prohibited" },
    .{ .acronym = "RESTRN", .code = 2, .value = "anchoring restricted" },
    .{ .acronym = "RESTRN", .code = 3, .value = "fishing prohibited" },
    .{ .acronym = "RESTRN", .code = 4, .value = "fishing restricted" },
    .{ .acronym = "RESTRN", .code = 5, .value = "trawling prohibited" },
    .{ .acronym = "RESTRN", .code = 6, .value = "trawling restricted" },
    .{ .acronym = "RESTRN", .code = 7, .value = "entry prohibited" },
    .{ .acronym = "RESTRN", .code = 8, .value = "entry restricted" },
    .{ .acronym = "RESTRN", .code = 9, .value = "dredging prohibited" },
    .{ .acronym = "RESTRN", .code = 10, .value = "dredging restricted" },
    .{ .acronym = "RESTRN", .code = 11, .value = "diving prohibited" },
    .{ .acronym = "RESTRN", .code = 12, .value = "diving restricted" },
    .{ .acronym = "RESTRN", .code = 13, .value = "no wake" },
    .{ .acronym = "RESTRN", .code = 14, .value = "area to be avoided" },
    .{ .acronym = "RESTRN", .code = 15, .value = "construction prohibited" },
    .{ .acronym = "RESTRN", .code = 16, .value = "discharging prohibited" },
    .{ .acronym = "RESTRN", .code = 17, .value = "discharging restricted" },
    .{
        .acronym = "RESTRN",
        .code = 18,
        .value = "industrial or mineral exploration/development prohibited",
    },
    .{
        .acronym = "RESTRN",
        .code = 19,
        .value = "industrial or mineral exploration/development restricted",
    },
    .{ .acronym = "RESTRN", .code = 20, .value = "drilling prohibited" },
    .{ .acronym = "RESTRN", .code = 21, .value = "drilling restricted" },
    .{ .acronym = "RESTRN", .code = 22, .value = "removal of historical artifacts prohibited" },
    .{ .acronym = "RESTRN", .code = 23, .value = "cargo transhipment (lightering) prohibited" },
    .{ .acronym = "RESTRN", .code = 24, .value = "dragging prohibited" },
    .{ .acronym = "RESTRN", .code = 25, .value = "stopping prohibited" },
    .{ .acronym = "RESTRN", .code = 26, .value = "landing prohibited" },
    .{ .acronym = "RESTRN", .code = 27, .value = "speed restricted" },
    .{ .acronym = "SIGGEN", .code = 1, .value = "automatically" },
    .{ .acronym = "SIGGEN", .code = 2, .value = "by wave action" },
    .{ .acronym = "SIGGEN", .code = 3, .value = "by hand" },
    .{ .acronym = "SIGGEN", .code = 4, .value = "by wind" },
    .{ .acronym = "STATUS", .code = 1, .value = "permanent" },
    .{ .acronym = "STATUS", .code = 2, .value = "occasional" },
    .{ .acronym = "STATUS", .code = 3, .value = "recommended" },
    .{ .acronym = "STATUS", .code = 4, .value = "not in use" },
    .{ .acronym = "STATUS", .code = 5, .value = "periodic/intermittent" },
    .{ .acronym = "STATUS", .code = 6, .value = "reserved" },
    .{ .acronym = "STATUS", .code = 7, .value = "temporary" },
    .{ .acronym = "STATUS", .code = 8, .value = "private" },
    .{ .acronym = "STATUS", .code = 9, .value = "mandatory" },
    .{ .acronym = "STATUS", .code = 10, .value = "destroyed/ruined" },
    .{ .acronym = "STATUS", .code = 11, .value = "extinguished" },
    .{ .acronym = "STATUS", .code = 12, .value = "illuminated" },
    .{ .acronym = "STATUS", .code = 13, .value = "historic" },
    .{ .acronym = "STATUS", .code = 14, .value = "public" },
    .{ .acronym = "STATUS", .code = 15, .value = "synchronized" },
    .{ .acronym = "STATUS", .code = 16, .value = "watched" },
    .{ .acronym = "STATUS", .code = 17, .value = "un-watched" },
    .{ .acronym = "STATUS", .code = 18, .value = "existence doubtful" },
    .{ .acronym = "SURTYP", .code = 1, .value = "reconnaissance/sketch survey" },
    .{ .acronym = "SURTYP", .code = 2, .value = "controlled survey" },
    .{ .acronym = "SURTYP", .code = 3, .value = "unsurveyed" },
    .{ .acronym = "SURTYP", .code = 4, .value = "examination survey" },
    .{ .acronym = "SURTYP", .code = 5, .value = "passage survey" },
    .{ .acronym = "SURTYP", .code = 6, .value = "remotely sensed" },
    .{ .acronym = "TECSOU", .code = 1, .value = "found by echo-sounder" },
    .{ .acronym = "TECSOU", .code = 2, .value = "found by side scan sonar" },
    .{ .acronym = "TECSOU", .code = 3, .value = "found by multi-beam" },
    .{ .acronym = "TECSOU", .code = 4, .value = "found by diver" },
    .{ .acronym = "TECSOU", .code = 5, .value = "found by lead-line" },
    .{ .acronym = "TECSOU", .code = 6, .value = "swept by wire-drag" },
    .{ .acronym = "TECSOU", .code = 7, .value = "found by laser" },
    .{ .acronym = "TECSOU", .code = 8, .value = "swept by vertical acoustic system" },
    .{ .acronym = "TECSOU", .code = 9, .value = "found by electromagnetic sensor" },
    .{ .acronym = "TECSOU", .code = 10, .value = "photogrammetry" },
    .{ .acronym = "TECSOU", .code = 11, .value = "satellite imagery" },
    .{ .acronym = "TECSOU", .code = 12, .value = "found by levelling" },
    .{ .acronym = "TECSOU", .code = 13, .value = "swept by side-scan sonar" },
    .{ .acronym = "TECSOU", .code = 14, .value = "computer generated" },
    .{ .acronym = "TOPSHP", .code = 1, .value = "cone, point up" },
    .{ .acronym = "TOPSHP", .code = 2, .value = "cone, point down" },
    .{ .acronym = "TOPSHP", .code = 3, .value = "sphere" },
    .{ .acronym = "TOPSHP", .code = 4, .value = "2 spheres" },
    .{ .acronym = "TOPSHP", .code = 5, .value = "cylinder (can)" },
    .{ .acronym = "TOPSHP", .code = 6, .value = "board" },
    .{ .acronym = "TOPSHP", .code = 7, .value = "x-shape (St. Andrew's cross)" },
    .{ .acronym = "TOPSHP", .code = 8, .value = "upright cross (St George's cross)" },
    .{ .acronym = "TOPSHP", .code = 9, .value = "cube, point up" },
    .{ .acronym = "TOPSHP", .code = 10, .value = "2 cones, point to point" },
    .{ .acronym = "TOPSHP", .code = 11, .value = "2 cones, base to base" },
    .{ .acronym = "TOPSHP", .code = 12, .value = "rhombus (diamond)" },
    .{ .acronym = "TOPSHP", .code = 13, .value = "2 cones (points upward)" },
    .{ .acronym = "TOPSHP", .code = 14, .value = "2 cones (points downward)" },
    .{ .acronym = "TOPSHP", .code = 15, .value = "besom, point up (broom or perch)" },
    .{ .acronym = "TOPSHP", .code = 16, .value = "besom, point down (broom or perch)" },
    .{ .acronym = "TOPSHP", .code = 17, .value = "flag" },
    .{ .acronym = "TOPSHP", .code = 18, .value = "sphere over rhombus" },
    .{ .acronym = "TOPSHP", .code = 19, .value = "square" },
    .{ .acronym = "TOPSHP", .code = 20, .value = "rectangle, horizontal" },
    .{ .acronym = "TOPSHP", .code = 21, .value = "rectangle, vertical" },
    .{ .acronym = "TOPSHP", .code = 22, .value = "trapezium, up" },
    .{ .acronym = "TOPSHP", .code = 23, .value = "trapezium, down" },
    .{ .acronym = "TOPSHP", .code = 24, .value = "triangle, point up" },
    .{ .acronym = "TOPSHP", .code = 25, .value = "triangle, point down" },
    .{ .acronym = "TOPSHP", .code = 26, .value = "circle" },
    .{ .acronym = "TOPSHP", .code = 27, .value = "two upright crosses (one over the other)" },
    .{ .acronym = "TOPSHP", .code = 28, .value = "T-shape" },
    .{ .acronym = "TOPSHP", .code = 29, .value = "triangle pointing up over a circle" },
    .{ .acronym = "TOPSHP", .code = 30, .value = "upright cross over a circle" },
    .{ .acronym = "TOPSHP", .code = 31, .value = "rhombus over a circle" },
    .{ .acronym = "TOPSHP", .code = 32, .value = "circle over a triangle pointing up" },
    .{ .acronym = "TOPSHP", .code = 33, .value = "other shape (see INFORM)" },
    .{ .acronym = "TRAFIC", .code = 1, .value = "inbound" },
    .{ .acronym = "TRAFIC", .code = 2, .value = "outbound" },
    .{ .acronym = "TRAFIC", .code = 3, .value = "one-way" },
    .{ .acronym = "TRAFIC", .code = 4, .value = "two-way" },
    .{ .acronym = "T_ACWL", .code = 1, .value = "better than 0.1 m and 10 minutes" },
    .{ .acronym = "T_ACWL", .code = 2, .value = "worse than 0.1 m or 10 minutes" },
    .{ .acronym = "T_MTOD", .code = 1, .value = "simplified harmonic method of tidal prediction" },
    .{ .acronym = "T_MTOD", .code = 2, .value = "full harmonic method of tidal prediction" },
    .{ .acronym = "T_MTOD", .code = 3, .value = "time and height difference non-harmonic method" },
    .{ .acronym = "VERDAT", .code = 1, .value = "mean low water springs" },
    .{ .acronym = "VERDAT", .code = 2, .value = "mean lower low water springs" },
    .{ .acronym = "VERDAT", .code = 3, .value = "mean sea level" },
    .{ .acronym = "VERDAT", .code = 4, .value = "lowest low water" },
    .{ .acronym = "VERDAT", .code = 5, .value = "mean low water" },
    .{ .acronym = "VERDAT", .code = 6, .value = "lowest low water springs" },
    .{ .acronym = "VERDAT", .code = 7, .value = "approximate mean low water springs" },
    .{ .acronym = "VERDAT", .code = 8, .value = "indian spring low water" },
    .{ .acronym = "VERDAT", .code = 9, .value = "low water springs" },
    .{ .acronym = "VERDAT", .code = 10, .value = "approximate lowest astronomical tide" },
    .{ .acronym = "VERDAT", .code = 11, .value = "nearly lowest low water" },
    .{ .acronym = "VERDAT", .code = 12, .value = "mean lower low water" },
    .{ .acronym = "VERDAT", .code = 13, .value = "low water" },
    .{ .acronym = "VERDAT", .code = 14, .value = "approximate mean low water" },
    .{ .acronym = "VERDAT", .code = 15, .value = "approximate mean lower low water" },
    .{ .acronym = "VERDAT", .code = 16, .value = "mean high water" },
    .{ .acronym = "VERDAT", .code = 17, .value = "mean high water springs" },
    .{ .acronym = "VERDAT", .code = 18, .value = "high water" },
    .{ .acronym = "VERDAT", .code = 19, .value = "approximate mean sea level" },
    .{ .acronym = "VERDAT", .code = 20, .value = "high water springs" },
    .{ .acronym = "VERDAT", .code = 21, .value = "mean higher high water" },
    .{ .acronym = "VERDAT", .code = 22, .value = "equinoctial spring low water" },
    .{ .acronym = "VERDAT", .code = 23, .value = "lowest astronomical tide" },
    .{ .acronym = "VERDAT", .code = 24, .value = "local datum" },
    .{ .acronym = "VERDAT", .code = 25, .value = "International Great Lakes Datum 1985" },
    .{ .acronym = "VERDAT", .code = 26, .value = "mean water level" },
    .{ .acronym = "VERDAT", .code = 27, .value = "lower low water large tide" },
    .{ .acronym = "VERDAT", .code = 28, .value = "higher high water large tide" },
    .{ .acronym = "VERDAT", .code = 29, .value = "nearly highest high water" },
    .{ .acronym = "VERDAT", .code = 30, .value = "highest astronomical tide (HAT)" },
    .{ .acronym = "WATLEV", .code = 1, .value = "partly submerged at high water" },
    .{ .acronym = "WATLEV", .code = 2, .value = "always dry" },
    .{ .acronym = "WATLEV", .code = 3, .value = "always under water/submerged" },
    .{ .acronym = "WATLEV", .code = 4, .value = "covers and uncovers" },
    .{ .acronym = "WATLEV", .code = 5, .value = "awash" },
    .{ .acronym = "WATLEV", .code = 6, .value = "subject to inundation or flooding" },
    .{ .acronym = "WATLEV", .code = 7, .value = "floating" },
};

const std = @import("std");

test "the transcribed table agrees with the S-57 attribute list" {
    // s57attributes.csv ships with the spec, outside this repo, so the path
    // comes from the environment and the test skips without it.
    //   TILE57_S57_ATTRIBUTES=<path>/s57attributes.csv zig build test
    const path = std.c.getenv("TILE57_S57_ATTRIBUTES") orelse return error.SkipZigTest;
    const a = std.testing.allocator;
    var threaded: std.Io.Threaded = .init(a, .{});
    defer threaded.deinit();
    const io = threaded.io();
    const bytes = std.Io.Dir.cwd().readFileAlloc(io, std.mem.span(path), a, .limited(4 << 20)) catch return error.SkipZigTest;
    defer a.free(bytes);

    var acronyms = std.StringHashMap(void).init(a);
    defer acronyms.deinit();
    var lines = std.mem.splitScalar(u8, bytes, '\n');
    _ = lines.next(); // header
    while (lines.next()) |line| {
        // A full name may hold a comma inside quotes, so fields are split on a
        // comma outside them.
        var fields: [4][]const u8 = .{ "", "", "", "" };
        var nf: usize = 0;
        var start: usize = 0;
        var in_q = false;
        const row = std.mem.trim(u8, line, "\r");
        for (row, 0..) |c, i| {
            if (c == '"') in_q = !in_q;
            if (c == ',' and !in_q) {
                if (nf < fields.len) fields[nf] = row[start..i];
                nf += 1;
                start = i + 1;
            }
        }
        if (nf < fields.len and start <= row.len) fields[nf] = row[start..];
        const code = std.fmt.parseInt(u16, fields[0], 10) catch continue;
        const acronym = fields[2];
        if (acronym.len == 0) continue;
        // Appendix A chapter 2's feature attributes, the set this table
        // transcribes. A `$` name is an S-52 presentation attribute, and
        // 190 to 192 are the S-52 symbology meta-attributes; neither belongs
        // to the object catalogue.
        if (code < 1 or code > 189) continue;
        if (acronym[0] == '$') continue;
        try acronyms.put(acronym, {});
    }
    try std.testing.expect(acronyms.count() > 100);

    // Every feature attribute the spec lists has a name here. CATHAF was the
    // one missing, and a feature carrying it reported a bare number.
    var missing = std.ArrayList([]const u8).empty;
    defer missing.deinit(a);
    var it = acronyms.keyIterator();
    while (it.next()) |k| {
        var found = false;
        for (attribute_names) |e| {
            if (std.mem.eql(u8, e.acronym, k.*)) found = true;
        }
        if (!found) try missing.append(a, k.*);
    }
    if (missing.items.len > 0) {
        for (missing.items) |m| std.debug.print("attribute absent from the table: {s}\n", .{m});
        return error.AttributeMissing;
    }

    // No entry here names an attribute the spec omits.
    for (attribute_names) |e| {
        if (e.acronym.len == 0) return error.EmptyAcronym;
    }
}
