//! bundle — S-101 portrayal asset emission as a LIBRARY module: colortables,
//! linestyles, sprite / pattern / sprite-mln atlases, built from the embedded
//! catalogue (or an on-disk PortrayalCatalog dir). Any consumer (the C ABI, a
//! Go/JS binding, another UI) builds the same assets. Also holds the ownership-
//! partition debug bake (`bakePartitionDebug`), which reuses the compositor's
//! partition-input helpers. Pure-Zig + libc (the sprite atlas builder needs
//! nanosvg/stb). The runtime compositor itself lives in the `compose` module.
//!
//! Each reader takes a `catalog_dir`: "" = the embedded catalogue (catalog module's
//! @embedFile'd registries), else `<catalog_dir>/{Symbols,LineStyles,AreaFills,
//! ColorProfiles}` on disk. The `*Bytes` helpers return the generated bytes (arena
//! owned) so an orchestrator reuses them without re-reading; the `emit*` helpers also
//! write them to a path. I/O is via the caller-supplied `std.Io` (no global state).

const std = @import("std");
const engine = @import("engine");
const style = @import("style");
const sprite = @import("sprite");
const compose = @import("compose"); // the runtime compositor (LoadedCov/toPlaneCells reused by the debug bake)
const embedded_assets = @import("catalog"); // S-101 portrayal assets embedded into the binary

// PortrayalCatalog sub-paths (relative to an on-disk catalog dir).
pub const COLOR_PROFILE_REL = "ColorProfiles/colorProfile.xml";
pub const LINESTYLES_REL = "LineStyles";
pub const SYMBOLS_REL = "Symbols";
pub const AREAFILLS_REL = "AreaFills";
pub const DEFAULT_CSS = "daySvgStyle.css";
// The other two palette stylesheets. All three carry the same class names and
// differ only in colour values, so a symbol rasterizes to the same cell at the
// same size under any of them and only its colours change.
pub const DUSK_CSS = "duskSvgStyle.css";
pub const NIGHT_CSS = "nightSvgStyle.css";

// ---- embedded catalogue assets (the `dir == ""` path of the readers) ---------

// Embedded Symbols/*.svg as sprite sources (id = file stem). Sorted at build time.
fn embeddedSymbols(a: std.mem.Allocator) ![]sprite.SvgSrc {
    const out = try a.alloc(sprite.SvgSrc, embedded_assets.symbols.len);
    for (embedded_assets.symbols, 0..) |e, i| out[i] = .{ .id = e.name, .svg = e.bytes };
    return out;
}

// Embedded AreaFills/*.xml as area-fill sources (id = file stem).
fn embeddedFills(a: std.mem.Allocator) ![]sprite.AreaFillSrc {
    const out = try a.alloc(sprite.AreaFillSrc, embedded_assets.areafills.len);
    for (embedded_assets.areafills, 0..) |e, i| out[i] = .{ .id = e.name, .xml = e.bytes };
    return out;
}

// Embedded LineStyles/*.xml as line-style sources (id = file stem).
pub fn embeddedLinestyles(a: std.mem.Allocator) ![]style.LineStyleSrc {
    const out = try a.alloc(style.LineStyleSrc, embedded_assets.linestyles.len);
    for (embedded_assets.linestyles, 0..) |e, i| out[i] = .{ .id = e.name, .xml = e.bytes };
    return out;
}

// Build the complex-line tessellation table (id -> linestyle.Info) from `srcs` and register
// it with scene before baking, so a named (symbolised) linestyle is drawn as its
// real dash runs + embedded symbols instead of a generic dashed stroke. Mirrors Go
// lsInfoFromCatalog; mm geometry is converted at the PresLib feature scale. Best
// effort — a malformed/short style is simply skipped. `gpa` outlives the bake.
pub fn registerLinestyles(gpa: std.mem.Allocator, srcs: []const style.LineStyleSrc) void {
    const px = engine.scene.linestyle.LINESTYLE_PX_PER_MM;
    for (srcs) |s| {
        const parsed = style.parseLineStyle(gpa, s.xml) catch continue;
        const period = parsed.interval_length * px;
        if (period < 0.5) continue; // no interval to tile (pure-symbol style)
        var runs = std.ArrayList([2]f64).empty;
        for (parsed.dashes) |d| {
            const lo = d.start * px;
            const hi = (d.start + d.length) * px;
            if (hi - lo > 1e-6) runs.append(gpa, .{ lo, hi }) catch {};
        }
        var syms = std.ArrayList(engine.scene.linestyle.Symbol).empty;
        for (parsed.symbols) |sym| syms.append(gpa, .{ .name = sym.reference, .offset_px = sym.position * px }) catch {};
        var width = parsed.pen_width * px;
        if (width < 0.6) width = 0.9; // S-52 minimum pen
        engine.scene.linestyle.registerLinestyle(gpa, s.id, .{
            .period_px = period,
            .on_runs = runs.items,
            .symbols = syms.items,
            .color_token = parsed.pen_color,
            .width_px = width,
        });
    }
}

// Embedded palette stylesheet bytes by file name (e.g. "daySvgStyle.css"); the
// lookup is by stem, so callers can pass a bare name. Null if not embedded.
fn embeddedCss(css_name: []const u8) ?[]const u8 {
    const stem = std.fs.path.stem(std.fs.path.basename(css_name));
    for (embedded_assets.css) |e| {
        if (std.mem.eql(u8, e.name, stem)) return e.bytes;
    }
    return null;
}

// The single embedded ColorProfiles/colorProfile.xml, or null if absent.
pub fn embeddedColorProfile() ?[]const u8 {
    for (embedded_assets.colorprofile) |e| return e.bytes;
    return null;
}

// Read the palette CSS: from the embedded catalogue (catalog_dir == "") or from
// <catalog_dir>/Symbols/<css_name> on disk.
fn readCss(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8) ![]const u8 {
    if (catalog_dir.len == 0) return embeddedCss(css_name) orelse error.MissingCss;
    const css_path = try std.fs.path.join(a, &.{ catalog_dir, SYMBOLS_REL, css_name });
    return std.Io.Dir.cwd().readFileAlloc(io, css_path, a, .unlimited);
}

// Emit colortables.json from a catalog dir. Returns the bytes (arena owned) so an
// orchestrator can reuse them without re-reading. Shared by the assets + bundle paths.
pub fn colorTablesBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8) ![]u8 {
    const xml = if (catalog_dir.len == 0)
        (embeddedColorProfile() orelse return error.MissingColorProfile)
    else blk: {
        const xml_path = try std.fs.path.join(a, &.{ catalog_dir, COLOR_PROFILE_REL });
        break :blk try std.Io.Dir.cwd().readFileAlloc(io, xml_path, a, .unlimited);
    };
    return style.colorTablesJson(a, xml);
}

pub fn emitColorTables(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, out_path: []const u8) ![]u8 {
    const json = try colorTablesBytes(io, a, catalog_dir);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = json });
    return json;
}

// Read every LineStyles/*.xml under catalog_dir and emit linestyles.json (dash
// patterns + placed symbols). Returns the bytes (arena owned). Shared by the
// assets + bundle paths. Mirrors the Go oracle's EmitS101 linestyles step.
pub fn linestylesBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8) ![]u8 {
    if (catalog_dir.len == 0) return style.linestylesJson(a, try embeddedLinestyles(a));
    const ls_dir_path = try std.fs.path.join(a, &.{ catalog_dir, LINESTYLES_REL });
    var dir = try std.Io.Dir.cwd().openDir(io, ls_dir_path, .{ .iterate = true });
    defer dir.close(io);

    var srcs = std.ArrayList(style.LineStyleSrc).empty;
    var walker = try dir.walk(a);
    defer walker.deinit();
    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".xml")) continue;
        const path = try a.dupe(u8, entry.path);
        const xml = dir.readFileAlloc(io, path, a, .unlimited) catch continue;
        const id = std.fs.path.stem(std.fs.path.basename(path));
        try srcs.append(a, .{ .id = id, .xml = xml });
    }
    return style.linestylesJson(a, srcs.items);
}

pub fn emitLinestyles(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, out_path: []const u8) ![]u8 {
    const json = try linestylesBytes(io, a, catalog_dir);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = json });
    return json;
}

// Read every Symbols/*.svg + the palette CSS and build the sprite atlas
// (sprite.json + sprite.png). Mirrors the Go oracle's SpriteAtlasS101FS.
pub fn spriteAtlasBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8) !sprite.Atlas {
    const srcs = try readSymbols(io, a, catalog_dir);
    const css = try readCss(io, a, catalog_dir, css_name);
    return sprite.spriteAtlas(a, srcs, css);
}

pub fn emitSprites(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, json_path: []const u8, png_path: []const u8) !sprite.Atlas {
    const atlas = try spriteAtlasBytes(io, a, catalog_dir, css_name);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = json_path, .data = atlas.json });
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = png_path, .data = atlas.png });
    return atlas;
}

// Read every Symbols/*.svg into a list (shared by the sprite + pattern atlases).
fn readSymbols(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8) ![]sprite.SvgSrc {
    if (catalog_dir.len == 0) return embeddedSymbols(a);
    const sym_dir_path = try std.fs.path.join(a, &.{ catalog_dir, SYMBOLS_REL });
    var dir = try std.Io.Dir.cwd().openDir(io, sym_dir_path, .{ .iterate = true });
    defer dir.close(io);
    var srcs = std.ArrayList(sprite.SvgSrc).empty;
    var walker = try dir.walk(a);
    defer walker.deinit();
    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".svg")) continue;
        const path = try a.dupe(u8, entry.path);
        const svg = dir.readFileAlloc(io, path, a, .unlimited) catch continue;
        try srcs.append(a, .{ .id = std.fs.path.stem(std.fs.path.basename(path)), .svg = svg });
    }
    return srcs.items;
}

// Read AreaFills/*.xml + Symbols/*.svg + the palette CSS and build the pattern
// atlas (patterns.json + patterns.png). Mirrors the Go oracle's PatternAtlasS101FS.
pub fn patternAtlasBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8) !sprite.Atlas {
    const fills = try readFills(io, a, catalog_dir);
    const symbols = try readSymbols(io, a, catalog_dir);
    const css = try readCss(io, a, catalog_dir, css_name);
    return sprite.patternAtlas(a, fills, symbols, css);
}

pub fn emitPatterns(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, json_path: []const u8, png_path: []const u8) !sprite.Atlas {
    const atlas = try patternAtlasBytes(io, a, catalog_dir, css_name);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = json_path, .data = atlas.json });
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = png_path, .data = atlas.png });
    return atlas;
}

// Read every AreaFills/*.xml under catalog_dir (shared by pattern + sprite-mln).
fn readFills(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8) ![]sprite.AreaFillSrc {
    if (catalog_dir.len == 0) return embeddedFills(a);
    const af_dir_path = try std.fs.path.join(a, &.{ catalog_dir, AREAFILLS_REL });
    var dir = try std.Io.Dir.cwd().openDir(io, af_dir_path, .{ .iterate = true });
    defer dir.close(io);
    var fills = std.ArrayList(sprite.AreaFillSrc).empty;
    var walker = try dir.walk(a);
    defer walker.deinit();
    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".xml")) continue;
        const path = try a.dupe(u8, entry.path);
        const xml = dir.readFileAlloc(io, path, a, .unlimited) catch continue;
        try fills.append(a, .{ .id = std.fs.path.stem(std.fs.path.basename(path)), .xml = xml });
    }
    return fills.items;
}

// Build the MapLibre sprite (sprite-mln) directly from the catalogue's Symbols +
// AreaFills + palette CSS. Mirrors the old scripts/build_sprite.py, in Zig.
pub fn spriteMlnBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, soundings: []const []const u8, ratio: f64) !sprite.Atlas {
    const symbols = try readSymbols(io, a, catalog_dir);
    const fills = try readFills(io, a, catalog_dir);
    const css = try readCss(io, a, catalog_dir, css_name);
    return sprite.spriteMln(a, symbols, fills, css, soundings, ratio);
}

/// Render one comma-joined symbol run (sounding digit stack) to a
/// pivot-centred RGBA image — the runtime answer to MapLibre's missing-image
/// event, for the runs no prebaked sheet can enumerate. Null when the run
/// names no known glyph. Caller owns the pixels (allocated in `a`).
pub fn symbolRunImage(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, run: []const u8, ratio: f64) !?sprite.RunImage {
    var arena = std.heap.ArenaAllocator.init(a);
    defer arena.deinit();
    const ar = arena.allocator();
    const symbols = try readSymbols(io, ar, catalog_dir);
    const css = try readCss(io, ar, catalog_dir, css_name);
    return sprite.renderSymbolRun(a, symbols, css, run, ratio);
}

// Emit sprite-mln.{json,png} + identical @2x copies (MapLibre requests @2x on
// HiDPI; a missing @2x sheet fails the whole sprite load).
pub fn emitSpriteMln(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, out_dir: []const u8, base: []const u8, soundings: []const []const u8) !sprite.Atlas {
    // The MapLibre style pipeline bakes the base (1x) sheet; @2x is a separate
    // (currently identical) copy the loader requires.
    const atlas = try spriteMlnBytes(io, a, catalog_dir, css_name, soundings, 1.0);
    for ([_][]const u8{ "", "@2x" }) |suffix| {
        const jn = try std.fmt.allocPrint(a, "{s}{s}.json", .{ base, suffix });
        const pn = try std.fmt.allocPrint(a, "{s}{s}.png", .{ base, suffix });
        try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = try std.fs.path.join(a, &.{ out_dir, jn }), .data = atlas.json });
        try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = try std.fs.path.join(a, &.{ out_dir, pn }), .data = atlas.png });
    }
    return atlas;
}

// Read + parse one cell (base .000 + sequential updates) from `dir`; null on
// any failure. The parsed cell allocates from c_allocator (thread-safe, and
// returns freed pages to the OS between cells — see chart.zig's gpa note).
fn readParseCell(io: std.Io, dir: std.Io.Dir, bpath: []const u8) ?engine.s57.Cell {
    const gpa = std.heap.c_allocator;
    const base = dir.readFileAlloc(io, bpath, gpa, .unlimited) catch return null;
    defer gpa.free(base);
    if (base.len == 0) return null;
    var ups = std.ArrayList([]const u8).empty;
    defer {
        for (ups.items) |ub| gpa.free(ub);
        ups.deinit(gpa);
    }
    const stem = bpath[0 .. bpath.len - 4];
    var u: u32 = 1;
    while (u <= 999) : (u += 1) {
        const upn = std.fmt.allocPrint(gpa, "{s}.{d:0>3}", .{ stem, u }) catch break;
        defer gpa.free(upn);
        const ub = dir.readFileAlloc(io, upn, gpa, .unlimited) catch break;
        ups.append(gpa, ub) catch {
            gpa.free(ub);
            break;
        };
    }
    return engine.s57.parseCellWithUpdates(gpa, base, ups.items) catch null;
}

/// THE eager cell-coverage loader: walk an ENC_ROOT, parse each cell once (base +
/// updates via readParseCell), and capture its M_COVR coverage + bbox + cscl + name
/// + date. One entry per stem (a boundary cell shared by two districts loads once).
/// Coverage is copied into `a` and survives the cell's deinit. "" / a missing dir
/// yields none; cells with no M_COVR are skipped. The single load path composed by
/// the cross-pack context, the partition debug bake, and the compositor.
fn loadCells(io: std.Io, a: std.mem.Allocator, path: []const u8) []compose.LoadedCov {
    if (path.len == 0) return &.{};
    var dir = std.Io.Dir.cwd().openDir(io, path, .{ .iterate = true }) catch return &.{};
    defer dir.close(io);
    var out = std.ArrayList(compose.LoadedCov).empty;
    var seen = std.StringHashMap(void).init(a);
    var walker = dir.walk(a) catch return &.{};
    defer walker.deinit();
    while (walker.next(io) catch null) |entry| {
        if (entry.kind != .file or !std.mem.endsWith(u8, entry.path, ".000")) continue;
        const stem = std.fs.path.stem(std.fs.path.basename(entry.path));
        if (seen.contains(stem)) continue;
        const stem_d = a.dupe(u8, stem) catch continue;
        seen.put(stem_d, {}) catch {};

        var cell = readParseCell(io, dir, entry.path) orelse continue;
        defer cell.deinit();
        const cov = cell.mcovrCoverage(a); // copied into `a`; survives cell.deinit()
        if (cov.len == 0) continue;
        var b = [4]f64{ 1e9, 1e9, -1e9, -1e9 };
        for (cov) |rings| for (rings) |ring| for (ring) |p| {
            b[0] = @min(b[0], p.lon());
            b[1] = @min(b[1], p.lat());
            b[2] = @max(b[2], p.lon());
            b[3] = @max(b[3], p.lat());
        };
        out.append(a, .{
            .name = stem_d,
            .date = a.dupe(u8, cell.dsid.isdt) catch "",
            .cscl = cell.params.cscl,
            .coverage = cov,
            .bounds = b,
        }) catch {};
    }
    return out.toOwnedSlice(a) catch &.{};
}

// A cyclic palette so adjacent ownership faces get distinct colours in the debug
// view; a face carries its colour as a `color` property for a trivial data-driven style.
const DEBUG_PALETTE = [_][]const u8{
    "#e6194b", "#3cb44b", "#ffe119", "#4363d8", "#f58231", "#911eb4", "#46f0f0", "#f032e6",
    "#bcf60c", "#fabebe", "#008080", "#e6beff", "#9a6324", "#fffac8", "#800000", "#aaffc3",
};

/// Bake a DEBUG PMTiles of the ownership PARTITION (which cell renders which ground),
/// NO portrayed content, for eyeballing the composite quilt. `band` < 0 emits the band
/// GOVERNING each zoom (the natural view); 0..5 (berthing..overview) emits only that
/// band's own map, at every zoom. Composes the single paths — loadCells + compose.toPlaneCells
/// + geometry.plane partition + the mvt/tile/pmtiles primitives — and STREAMS tiles (one
/// tier + one zoom resident) so it scales to the whole corpus. Returns the cell count;
/// `out_path` is a single `.pmtiles` file.
pub fn bakePartitionDebug(io: std.Io, gpa: std.mem.Allocator, root_path: []const u8, out_path: []const u8, minzoom: u8, maxzoom_arg: u8, band: i8) !usize {
    const geometry = engine.geometry;
    const maxzoom = @min(maxzoom_arg, @as(u8, 16));

    var arena = std.heap.ArenaAllocator.init(gpa);
    defer arena.deinit();
    const a = arena.allocator();

    // Single load + adapt paths. Reach-cap each cell exactly as the compositor does
    // (band terms only — a native per-cell bake never exceeds its band window), so the
    // debug quilt shows the partition the compositor actually composes with, not a
    // hypothetical full pool.
    const loaded = loadCells(io, a, root_path);
    if (loaded.len == 0) return error.NoGeometry;
    const cells = try compose.toPlaneCells(a, loaded);
    for (cells) |*c| c.reach = compose.bandReach(c.cscl);

    // Union bbox (E7) for the header, so a viewer opens on the data not the world.
    var ubox = [4]i32{ std.math.maxInt(i32), std.math.maxInt(i32), std.math.minInt(i32), std.math.minInt(i32) };
    for (loaded) |c| {
        ubox[0] = @min(ubox[0], deg7(c.bounds[0]));
        ubox[1] = @min(ubox[1], deg7(c.bounds[1]));
        ubox[2] = @max(ubox[2], deg7(c.bounds[2]));
        ubox[3] = @max(ubox[3], deg7(c.bounds[3]));
    }
    std.debug.print("partition-debug: {d} cells from {s}, z{d}-{d}, band {d}\n", .{ loaded.len, root_path, minzoom, maxzoom, band });

    // Stream tiles (gzipped + deduped) so the whole archive never lives uncompressed.
    var sw = engine.pmtiles.StreamWriter.init(gpa);
    defer sw.deinit();
    var zoom_arena = std.heap.ArenaAllocator.init(gpa); // one zoom's tiles at a time
    defer zoom_arena.deinit();

    if (band >= 0) {
        // One band's own map: build its tier once, emit across every zoom.
        const bandv: engine.bake_enc.Band = @enumFromInt(@as(u8, @intCast(@min(band, @as(i8, 5)))));
        const tier = engine.bake_enc.bandZooms(bandv).min;
        const faces = try geometry.plane.ownedAtTierIndexed(gpa, cells, tier);
        defer geometry.plane.freeOwned(gpa, faces);
        var z: u8 = minzoom;
        while (z <= maxzoom) : (z += 1) {
            _ = zoom_arena.reset(.retain_capacity);
            try emitFacesZoom(&sw, zoom_arena.allocator(), faces, loaded, z, tier);
        }
    } else {
        // Merged: the band governing each zoom. Build that tier lazily, one resident at
        // a time (coarse→fine as z rises), so the finest tier is only built if reached.
        const floors = try distinctFloorsDesc(a, cells);
        var cur_tier: i16 = -1;
        var cur_faces: []geometry.plane.OwnedCell = &.{};
        defer if (cur_tier >= 0) geometry.plane.freeOwned(gpa, cur_faces);
        var z: u8 = minzoom;
        while (z <= maxzoom) : (z += 1) {
            const t = governingTier(floors, z);
            if (cur_tier != @as(i16, t)) {
                if (cur_tier >= 0) geometry.plane.freeOwned(gpa, cur_faces);
                cur_faces = try geometry.plane.ownedAtTierIndexed(gpa, cells, t);
                cur_tier = t;
            }
            _ = zoom_arena.reset(.retain_capacity);
            try emitFacesZoom(&sw, zoom_arena.allocator(), cur_faces, loaded, z, t);
        }
    }

    // Frame a viewer on the data (a zoom where the bbox is ~2 tiles wide).
    const span_deg = @max(0.01, @as(f64, @floatFromInt(ubox[2] - ubox[0])) / 1e7);
    const cz: u8 = @intFromFloat(std.math.clamp(std.math.log2(720.0 / span_deg), @as(f64, @floatFromInt(minzoom)), @as(f64, @floatFromInt(maxzoom))));
    const bytes = try sw.finishBytes(.{
        // MapLibre/pmtiles.io build their style from `vector_layers`; without it the
        // "partition" layer is invisible to a viewer no matter the geometry.
        .metadata_json = "{\"name\":\"partition-debug\",\"format\":\"pbf\",\"vector_layers\":[{\"id\":\"partition\",\"fields\":{\"cell\":\"String\",\"cscl\":\"Number\",\"band\":\"Number\",\"tier\":\"Number\",\"oi\":\"Number\",\"color\":\"String\"}},{\"id\":\"labels\",\"fields\":{\"cell\":\"String\"}}]}",
        .tile_type = .mvt,
        .min_lon_e7 = ubox[0],
        .min_lat_e7 = ubox[1],
        .max_lon_e7 = ubox[2],
        .max_lat_e7 = ubox[3],
        .center_zoom = cz,
    });
    defer gpa.free(bytes);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = bytes });
    return loaded.len;
}

// deg → E7 integer.
fn deg7(d: f64) i32 {
    return @intFromFloat(@round(d * 1e7));
}

// Distinct band floors, DESCENDING (finest floor first) — the tier ladder.
fn distinctFloorsDesc(a: std.mem.Allocator, cells: []const engine.geometry.plane.Cell) ![]u8 {
    var seen = std.AutoHashMap(u8, void).init(a);
    for (cells) |c| try seen.put(c.band_floor, {});
    const out = try a.alloc(u8, seen.count());
    var it = seen.keyIterator();
    var i: usize = 0;
    while (it.next()) |k| : (i += 1) out[i] = k.*;
    std.mem.sort(u8, out, {}, comptime std.sort.desc(u8));
    return out;
}

// The band floor governing zoom `z`: the largest floor ≤ z, or the coarsest if z is
// below every floor (so zooming out never falls off the bottom).
fn governingTier(floors_desc: []const u8, z: u8) u8 {
    for (floors_desc) |t| if (t <= z) return t;
    return floors_desc[floors_desc.len - 1];
}

/// Project + clip one tier's faces into the tiles of zoom `z` and stream them to `sw`
/// (layer "partition"). `sa` is a per-zoom arena the caller resets, so only one zoom's
/// tiles are resident. Reuses tile.project/clipPolygon + scene.orientAreaRings (the MVT
/// winding authority) + mvt.encode.
fn emitFacesZoom(sw: *engine.pmtiles.StreamWriter, sa: std.mem.Allocator, faces: []const engine.geometry.plane.OwnedCell, loaded: []const compose.LoadedCov, z: u8, tier: u8) !void {
    const mvt = engine.mvt;
    const tile = engine.tile;
    const scale: f64 = @floatFromInt(@as(u64, 1) << @intCast(z));
    const TileKey = struct { x: u32, y: u32 };
    const TileFeat = struct { polys: std.ArrayList(mvt.Feature), labels: std.ArrayList(mvt.Feature) };
    var tilemap = std.AutoHashMap(TileKey, TileFeat).init(sa);

    for (faces) |face| {
        if (face.owned.len == 0) continue;
        const lc = loaded[face.index];

        var fb = [4]f64{ 1e9, 1e9, -1e9, -1e9 };
        for (face.owned) |ring| for (ring) |p| {
            const lon = @as(f64, @floatFromInt(p.x)) / 1e7;
            const lat = @as(f64, @floatFromInt(p.y)) / 1e7;
            fb[0] = @min(fb[0], lon);
            fb[1] = @min(fb[1], lat);
            fb[2] = @max(fb[2], lon);
            fb[3] = @max(fb[3], lat);
        };
        const w_tl = tile.lonLatToWorld(fb[0], fb[3]);
        const w_br = tile.lonLatToWorld(fb[2], fb[1]);
        const tx0 = compose.worldAxisToTile(w_tl[0], scale);
        const tx1 = compose.worldAxisToTile(w_br[0], scale);
        const ty0 = compose.worldAxisToTile(w_tl[1], scale);
        const ty1 = compose.worldAxisToTile(w_br[1], scale);

        const props = try sa.dupe(mvt.Prop, &.{
            .{ .key = "cell", .value = .{ .string = lc.name } },
            .{ .key = "cscl", .value = .{ .int = lc.cscl } },
            .{ .key = "band", .value = .{ .int = @intFromEnum(engine.bake_enc.bandOf(lc.cscl)) } },
            .{ .key = "tier", .value = .{ .int = tier } },
            .{ .key = "oi", .value = .{ .int = @intCast(face.index) } },
            .{ .key = "color", .value = .{ .string = DEBUG_PALETTE[face.index % DEBUG_PALETTE.len] } },
        });

        var tx = tx0;
        while (tx <= tx1) : (tx += 1) {
            var ty = ty0;
            while (ty <= ty1) : (ty += 1) {
                var parts = std.ArrayList([]const mvt.Point).empty;
                for (face.owned) |ring| {
                    const proj = try sa.alloc(mvt.Point, ring.len);
                    for (ring, 0..) |p, k| proj[k] = tile.project(@as(f64, @floatFromInt(p.x)) / 1e7, @as(f64, @floatFromInt(p.y)) / 1e7, z, tx, ty, tile.EXTENT);
                    const clipped = try tile.clipPolygon(sa, proj, tile.Box.default(tile.EXTENT, 256));
                    if (clipped.len >= 3) try parts.append(sa, clipped);
                }
                if (parts.items.len == 0) continue;
                const oriented = try engine.mvt.orientAreaRings(sa, parts.items);
                const gop = try tilemap.getOrPut(.{ .x = tx, .y = ty });
                if (!gop.found_existing) gop.value_ptr.* = .{ .polys = .empty, .labels = .empty };
                try gop.value_ptr.polys.append(sa, .{ .geom_type = .polygon, .parts = oriented, .properties = props });

                // Label this face's part IN THIS tile, at the centre of its clipped
                // extent, so the owning cell name is readable wherever the face shows
                // (layer "labels"). MapLibre collision-dedups the repeats across tiles.
                var lb = [4]i32{ std.math.maxInt(i32), std.math.maxInt(i32), std.math.minInt(i32), std.math.minInt(i32) };
                for (oriented) |ring| for (ring) |p| {
                    lb[0] = @min(lb[0], p.x);
                    lb[1] = @min(lb[1], p.y);
                    lb[2] = @max(lb[2], p.x);
                    lb[3] = @max(lb[3], p.y);
                };
                const lpt = try sa.alloc(mvt.Point, 1);
                lpt[0] = .{ .x = @divTrunc(lb[0] + lb[2], 2), .y = @divTrunc(lb[1] + lb[3], 2) };
                const lparts = try sa.alloc([]const mvt.Point, 1);
                lparts[0] = lpt;
                try gop.value_ptr.labels.append(sa, .{ .geom_type = .point, .parts = lparts, .properties = try sa.dupe(mvt.Prop, &.{.{ .key = "cell", .value = .{ .string = lc.name } }}) });
            }
        }
    }

    var it = tilemap.iterator();
    while (it.next()) |kv| {
        var layers = std.ArrayList(mvt.Layer).empty;
        if (kv.value_ptr.polys.items.len > 0) try layers.append(sa, .{ .name = "partition", .features = kv.value_ptr.polys.items });
        if (kv.value_ptr.labels.items.len > 0) try layers.append(sa, .{ .name = "labels", .features = kv.value_ptr.labels.items });
        if (layers.items.len == 0) continue;
        const enc = try mvt.encode(sa, .{ .layers = layers.items });
        try sw.add(z, kv.key_ptr.x, kv.key_ptr.y, enc);
    }
}

test {
    // A test binary rooted here links lua_shim.c through engine's portray
    // module but analyses only what its tests reach. Referencing engine scans
    // bake_root.zig, whose comptime block emits the shim's C-ABI accessors.
    _ = engine;
}
